- .github/workflows/rust.yml
Cargo culted from cgwalters/openat-ext
> ci: Add GH action for Rust

- lib/src/tar/export.rs
It's already a member of the exporter struct.
> tar/export: Drop duplicate repo param

- .github/workflows/rust.yml
See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
> actions: Set read-only flag

- cli/Cargo.toml
- cli/src/main.rs
- lib/src/container/import.rs
- lib/src/tar/import.rs
- lib/tests/it/main.rs
This demos a lot better than watching the CLI sit there and
do nothing until done!
> cli+container: Add support for progress

- lib/src/tar/import.rs
Instead of heap allocating and zero initializing one for each object.
> tar/import: Cache a reusable buffer

- lib/src/cli.rs
This will be needed for https://github.com/coreos/fedora-coreos-tracker/issues/828
so coreos-assembler can find the commit it imported.
> cli: Add `container import --write-ref` option

- .github/workflows/rust.yml
- lib/src/container/import.rs
- lib/src/container/mod.rs
- lib/src/container/skopeo.rs
- lib/src/ima.rs
- lib/src/tar/import.rs
- lib/tests/it/main.rs
Came up in review of another PR; clippy is good.
> Fix all clippy lints

- lib/src/cli.rs
- lib/src/container/export.rs
- lib/src/container/oci.rs
- lib/tests/it/main.rs
Part of replacing the cosa/RHCOS oscontainer bits, which sets
labels today with things like specific RPM versions.
> container/export: Add ability to configure exported container

- lib/src/tar/export.rs
I noticed we were just using an 8k buffer; bumping this up to
128k as used by coreutils cat is slightly faster here (just a few
percent), but it also makes `strace` way less noisy.
> tar/export: Add larger buffer for reads

- docs/questions-and-answers.md
Credits to Colin for providing the "answers" side of "questions and answers".
I've tried to organize my notes a little bit and mostly copy and pasted them here, but I'm sure there are still some inaccuracies, so please let me know if my understanding is incorrect anywhere! Also let me know if any questions might be irrelevant to this project.
> Add Questions and Answers section

- lib/src/variant_utils.rs
Since this comes up a lot in ostree APIs.
Closes: https://github.com/ostreedev/ostree-rs/issues/5
> variant_utils: Add API to create an `as` variant

- lib/src/container/import.rs
We're hitting this race condition when teaching rpm-ostree to
consume container images.  The current skopeo code creates
two async tasks, one to read from the FIFO (pipe), and one
to wait on the child process.
Currently when we find the layer tarball we're expecting,
we close the FIFO.  This causes any further messages from
skopeo to fail with `EPIPE` which it's not expecting, which
will then cause skopeo to exit with a failure.
Rework the logic here so that we hold open the FIFO until
the process has exited.  The "tar parsing" import code
takes ownership of the stream, but then passes it back
to the caller.
> container/import: Only close skopeo fifo once the process has exited

- README.md
> README.md: Note why ostree tar is lossy

- cli/Cargo.toml
- lib/Cargo.toml
This updates the repository URLs to the new location.
> cargo: fix repository location

- lib/src/ima.rs
While in theory using the unsafe path could be more efficient,
in practice I think the impedance mismatch between e.g. Rust `&str`
and C strings requires duplicating anyways.  So just build up
a Rust data structure and then convert it all in one go.
> ima: Use new GVariant code, drop unsafe

- lib/src/tar/import.rs
- lib/tests/it/main.rs
tar/import: Minor state machine cleanup
Validate upfront that we only get xattrs with content objects;
this way the rest of the match doesn't need to ignore the boolean.
---
tar: Validate we get an error with an empty tarball
And then we can later extend this to more error cases.
---
> Sign verify tar prep

- lib/src/cli.rs
- lib/src/container/skopeo.rs
- lib/src/tar/import.rs
> lib: Fix misc clippy issues

- lib/tests/it/main.rs
It's handy to have some level of predictability, so verify
that the tar stream we output for a given commit is
bit-for-bit identical when invoked twice - with a one
second delay to flush out at least things like modification
times.
We will never be able to assert on a particular checksum, because
e.g. things like the gzip algorithm may compress differently
when the code changes.  Related discussion in
https://github.com/cgwalters/git-evtag#tarball-reproducibility
> tests: Verify that exported tar is bit-for-bit identical

- lib/src/container/import.rs
- lib/src/container/oci.rs
Prep for derivation, where we want to find all layers.  Move
this to a method on `Manifest`, and add a unit test for it.
Also while we're here, change the function to borrow and not clone
on general principle.
> lib/container: Split off helper to find all layers into oci

- lib/src/container/imageproxy.rs
- lib/src/container/import.rs
- lib/src/container/oci.rs
Depends https://github.com/ostreedev/ostree-rs-ext/pull/101
---
Trying to pull from `containers-storage:` it actually exports
uncompressed tarballs, which makes sense.
Clean up our layer handling to correctly match on the media
type and return the correct decompressor.  This is also prep
for handling zstd.
>  lib/container: Correctly handle uncompressed layers

- lib/src/tar/import.rs
- lib/src/tokio_util.rs
This is the inverse of the previous API; we have cases today
where we're spawning a helper blocking thread that calls functions
internally that use `GCancellable`, but we weren't passed one.
See https://github.com/gtk-rs/gtk-rs-core/issues/240
> tokio_util: Add API to do GLib+`GCancellable` from `async fn`

- lib/src/tar/write.rs
Using `--selinux-policy-from-base` is very convenient but wrong
here because it means that each derived commit also has the whole
base filesystem tree, which greatly obscures its logical content.
Instead, we get the base when we dynamically union things at the end.
As noted the API we really want here is
https://github.com/ostreedev/ostree/pull/2447
but it will take a bit for ostree to release with it.
And even once it does, we need to do some other changes to switch
over to parsing the tarball directly too.
> tar/write: Don't actually derive from base when using selinux

- lib/Cargo.toml
- lib/src/tar/import.rs
This lets us use the auto transaction bits.
> Bump to ostree 0.13.2

- lib/src/cli.rs
A bit more rightward drift, but less duplication.  Prep for
further commands.
> cli: Switch to nested match for container opts

- README.md
- Include an architecture diagram
- Split off the "why ostree with containers" detail bits to
separate file
- Describe a little bit more about layering now that it's supported
> README.md: Various updates/reworking

- lib/src/cli.rs
- lib/src/container/deploy.rs
- lib/src/container/ociwriter.rs
- lib/src/container/store.rs
- lib/src/container/unencapsulate.rs
- lib/src/refescape.rs
Fix `clippy::needless_borrow`
---
Fix two minor clippy lints
---
> Misc clippy

- ostree-and-containers.md
I split this off in
https://github.com/ostreedev/ostree-rs-ext/pull/141
But forgot to `git add` apparently.
> ostree-and-containers.md: Forgot to `git add` in a previous PR

- lib/Cargo.toml
> Bump to 0.5.0

- lib/src/tar/export.rs
I'm hitting an error on symlink length exporting Fedora Silverblue,
this helped me debug via:
```
$ /var/srv/walters/src/github/ostreedev/ostree-rs-ext/target/debug/ostree-ext-cli container encapsulate --repo=/ostree/repo f8e7ed0ee87a8ae48eb779c085f4fffddb824c5830e43715e6c92799a678d806 oci:/var/tmp/fedora-silverblue
error: Building oci: Writing ostree root to blob: Exporting commit: Writing content symlink: 87c8834da3bad596352375ff413bca064584f184bdd6ba1764293d137249e168: provided value is too long when setting link name for
$ ostree ls -C -R f8e7ed0ee87a8ae48eb779c085f4fffddb824c5830e43715e6c92799a678d806 | grep 87c8834da3bad596352375ff413bca064584f184bdd6ba1764293d137249e168
l00777 0 0      0 87c8834da3bad596352375ff413bca064584f184bdd6ba1764293d137249e168 …
```
> tar/export: Add more error prefixing

- lib/src/container/encapsulate.rs
- lib/src/container/ociwriter.rs
This is prep for commit splitting into separate blobs, to help
identify layers which are "ostree native" and those which are not.
It turns out since the Docker schema:
https://docs.docker.com/registry/spec/manifest-v2-2/
does not have annotations, they simply get discarded, so we can't rely
on this.
But...I wrote this code and I think it makes sense, so let's ship it
anyways.
> container/encapsulate: Write `ostree.encapsulated` annotation on layer

- lib/src/container/unencapsulate.rs
A while ago I split up the APIs so we support
- fetching just the manifest
- fetching an image from an already fetched manifest
- combining the two
However, the latter API ended up creating two proxies, one to
fetch the manifest and one for the rest.  That's inefficent,
so rework things so we have internal APIs that take a proxy and
only create it once.
Just noticed when reading the code for unrelated reasons.
> container/unencapsulate: Only create one proxy in default pull path

- lib/src/container/store.rs
- lib/tests/it/main.rs
Prep for using this for copies.
> container/store: Also parse and save image configuration

- lib/src/container/mod.rs
Followup to https://github.com/ostreedev/ostree-rs-ext/pull/187/commits/0ec9e980d3274a3a8fe2f99d3fd253c8d03fb160
Motivated by dropping some `.unwrap()` calls.
> container: Use more `split_once`

- lib/src/cli.rs
- lib/src/commit.rs
- lib/src/lib.rs
Adds initial validation of /var per: https://github.com/ostreedev/ostree-rs-ext/issues/159#issuecomment-1006033596
> lib/src/cli: Add commit verb that validates /var

- lib/Cargo.toml
- lib/src/integrationtest.rs
Depends https://github.com/containers/oci-spec-rs/pull/87
> integrationtest: Use mut setters from oci-spec

- lib/src/tar/export.rs
- lib/tests/it/main.rs
This ensures compatibility with older clients, which we need
to pass the rpm-ostree upgrade test.
> tar/export: Continue injecting mode bits in format version 0

- lib/src/tar/import.rs
I was just reading this and noticed we can simplify it.
> lib/tar: Simplify import code, minor comment tweaks

- .github/workflows/rust.yml
This one is updated automatically.
> ci: Switch to more official FCOS image

- lib/src/container/ocidir.rs
Followup to https://github.com/ostreedev/ostree-rs-ext/pull/206/commits/e0c4c849d9901e0de03744a6200117424f1b7158
This is notably more efficient than deep cloning all the elements.
Just noticed while reading the code for an unrelated reason.
> ocidir: More direct use of direct `_mut()` methods

- lib/src/container/encapsulate.rs
- lib/src/container/skopeo.rs
This code predated our dependency on `experimental-image-proxy`,
so we can now safely carry a hard dependency on a new enough
skopeo and drop the pile of hacks here.
> Hard depend on `skopeo copy --digestfile`

- lib/src/tar/export.rs
- lib/src/tar/import.rs
This switches hardlinks to use full paths as link targets. Otherwise
a plain tar unpacking may get really confused by the leading `../`
(and may actually decide to strip it as a security concern).
> tar/export: use full path as link target

- lib/src/cli.rs
It's stuff like this that is just *so elegant* in Rust.
> cli: Use structopt's `TryFrom` support for parsing `ostree::Repo`

- lib/src/cli.rs
- lib/src/tar/write.rs
> tar: Add a debug function to filter tar

- lib/src/tar/export.rs
> tar/export: Extract a helper for writing content hardlink

- lib/Cargo.toml
- lib/src/container/store.rs
- lib/src/container/unencapsulate.rs
This works on top of https://github.com/containers/containers-image-proxy-rs/pull/29
> Update to latest containers-image-proxy API

- lib/tests/it/main.rs
Seeing the full `ostree_ext::container::store::` a lot is too
verbose.  Consistently shorten this to just `store::`.
> tests: Consistently use `store::`

- .github/workflows/rust.yml
Some follow up from seeing https://www.reddit.com/r/rust/comments/ug4utz/tips_for_speeding_up_rust_builds_times_in_ci_we/
> ci: Split build vs test, try cache keys

- lib/src/container/encapsulate.rs
- lib/src/container/skopeo.rs
Prep for some signing work, but this also may be generally
useful in the future.
---
> container: Factor out helper to copy image reference

- lib/src/container/store.rs
- lib/src/tar/export.rs
store: Extract a helper function to find ostree layer
Prep for further work around signature injection.
---
tar/export: Extract helper functions
Prep for signature rewriting.
---
> Two signature injection prep patches

- lib/src/container/ocidir.rs
Prep for signature injection work.
> ocidir: Various new internal API improvements

- lib/Cargo.toml
Basically just picks up the new detached metadata bits.
> lib: Release 0.7.3

- lib/src/cli.rs
- lib/src/fixture.rs
- lib/src/integrationtest.rs
> Add a helper to generate a text fixture externally

- lib/src/chunking.rs
- lib/src/container/encapsulate.rs
- lib/src/tar/export.rs
A few commits split from https://github.com/ostreedev/ostree-rs-ext/pull/312 to try to figure out why tests are hanging.
> Tar refactor 0

- .github/workflows/rust.yml
I want to be able to run them manually too to sanity check things.
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#defining-inputs-for-manually-triggered-workflows
> ci: Allow manually invoking tests

- lib/src/container/encapsulate.rs
Pass the `ExportOpts` farther down into processing; prep for
adding more fields and using them there.
Add a helper method that gives us the compression from the options,
instead of open-coding it.
> container/encapsulate: Pass down options farther

- lib/tests/it/main.rs
Most of the expected entries are common between v0 and v1.
Prep for some further code refactoring.
> tests: Deduplicate tar structure validation code

- lib/Cargo.toml
It's the latest version of the project.
> lib: Bump tokio-util

- lib/src/commit.rs
xref https://github.com/coreos/rpm-ostree/issues/4017
I want to have rpm-ostree use this API, but in order to do so in a backwards compatible way we need a mode that just warns but continues.
> commit: Add an API to warn but continue on files in `/var`

- lib/src/objectsource.rs
- lib/src/tar/import.rs
Caught by newer clippy than is in our MSRV.
> Fix two minor clippy lints

- lib/Cargo.toml
Nothing major/critical but I am specifically wanting to get the image deploy fix out.
> Release 0.8.8

- ci/container-build-integration.sh
https://github.com/coreos/coreos-layering-examples/pull/37 broke this CI, attempting... to fix it.
> ci: use Containerfile instead of Dockerfile

- lib/Cargo.toml
Just two changes, one feature for better systemd logging, and one for unauthenticated fetches.
> lib: release 0.8.9

- .github/workflows/rust.yml
- ci/container-build-integration.sh
- ci/priv-integration.sh
> ci: Adapt to new FCOS image location

- lib/src/container/store.rs
- lib/tests/it/main.rs
A while ago we added APIs to do this, but we should really do it by default when fetching upgraded images.  Otherwise we effectively leak space.
> container: Prune image layers by default

- lib/src/integrationtest.rs
- lib/tests/it/main.rs
xref https://github.com/ostreedev/ostree-rs-ext/issues/405
This test case reproduces the failure when we're trying to import a tar archive with hardlinks into `/sysroot`.
> tests: Add a case to reproduce hardlink to /sysroot failure

- ci/priv-integration.sh
Prep commit for #396 
Fails for: ostree-ext-cli container image pull $osrepo ostree-unverified-image:containers-storage:$image
> Ensure integration testing fails for pulling from containers-storage 

- lib/Cargo.toml
- lib/src/chunking.rs
- lib/src/cli.rs
- lib/src/container/deploy.rs
- lib/src/container/store.rs
- lib/src/diff.rs
- lib/src/fixture.rs
- lib/src/ima.rs
- lib/src/integrationtest.rs
- lib/src/tar/export.rs
- lib/src/tar/import.rs
- lib/src/tar/write.rs
- lib/src/tokio_util.rs
- lib/tests/it/main.rs
This requires https://github.com/gtk-rs/gtk-rs-core/pull/820
> Bump semver to 0.10, ostree 0.17 (and glib 0.16) and cap-std 1.0

- ci/priv-integration.sh
- lib/Cargo.toml
- lib/src/container/store.rs
- lib/src/container/unencapsulate.rs
fixes: #153
Uses
containers-image-proxy-rs: https://github.com/containers/containers-image-proxy-rs/pull/37
skopeo: https://github.com/containers/skopeo/pull/1802
> Fix pulling from containers-storage

- README.md
It looks nicer and is more maintainable.
> README.md: Switch to mermaid for arch visualization

- README.md
We need a ton more docs here, but this is a start.
> README.md: Describe chunking briefly

- README.md
> README.md: Link to bootc

- lib/src/container/store.rs
To aid debugging https://github.com/coreos/rpm-ostree/issues/4185
> store: Print which ref is missing

- lib/src/container/store.rs
This is another necessary fix for
https://github.com/coreos/rpm-ostree/pull/4204
> store: Make failure to query base image non-fatal

- lib/src/container/mod.rs
In rpm-ostree we provide a custom config to override the isolation user, calling the merge function.  But the logic for idempotency of auth handling was buggy - it needed to consider having `auth_data` already specified.
> container: Fix idempotency of config defaults merging

- lib/tests/it/main.rs
This was all hardcoded to V1, so just drop the conditionals.
> tests: Drop even more export layout bits

- lib/src/cli.rs
- lib/src/container/mod.rs
Allows to compare the content between two OCI compliant images
> Add ostree-ext-cli container compare image1 image2

- ci/priv-integration.sh
Compares an image against itself to result in a 0 delta
> Add basic check to --compare-with-build

- lib/src/tar/export.rs
> tar: Drop dead code for format version 0

- ci/priv-integration.sh
A new enough skopeo got shipped, so let's update our CI!
> ci: We can now pull from containers-storage

- lib/src/commit.rs
We've designed a conflicting system; the `ostree container commit` command today will nuke `/var`, but in most implementations this will create a whiteout, which the deploy command warns about.
Also, too many commands expect `/var/tmp` to exist; so creating *further* derived images after `ostree container commit` is problematic.
Instead, let's cave here and prune everything except `/var/tmp`, and also change the deploy code to not warn about empty directories there.
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/468
> commit: Don't prune `/var`

- lib/src/objectsource.rs
> objectsource: Some docs additions

- lib/src/container/encapsulate.rs
- lib/src/container/store.rs
- lib/src/container/update_detachedmeta.rs
Since we're making a semver-incompatible API change, and we don't support V0 anymore, drop the public API touchpoints here.
> Drop container ExportLayout from public interface

- lib/src/container/store.rs
- lib/tests/it/main.rs
Solves: #480 
store: Change order of layers to ostree_commit, packaged layers
main: Identify correctly the updated layers
> Modify test_container_chunked

- lib/Cargo.toml
Just two minor changes, but I'd like to have bootc use them.
> Release 0.11.2

- lib/Cargo.toml
> Release 0.11.3

- lib/Cargo.toml
Just to keep the fixes flowing.
> Release 0.11.5

- lib/Cargo.toml
Just a collection of relatively minor things, but let's keep the train going.
> Release 0.11.6

- lib/Cargo.toml
> Release 0.12.1

- lib/src/commit.rs
I got confused by the statx API here; it just happened to work because we were ignoring the mask.
This version comes with a test case too.
> lib: Fix mountpoint check

- lib/src/container/encapsulate.rs
We need to support e.g.
`rpm-ostree compose container-encapsulate --format=oci manifest.yaml oci:foo:42`
> container/encapsulate: Fix pushing to OCI directories with a tag

- lib/Cargo.toml
Just two small changes, plus a new man page.
> Release 0.12.2

- lib/Cargo.toml
Mainly want to use new apis in bootc.
> Release 0.12.3

- ci/priv-integration.sh
- lib/src/cli.rs
For ease of introspection; xref e.g.
https://github.com/dustymabe/osbuild/pull/10
> cli: Add commands to output manifest and config

- lib/Cargo.toml
Just rolling up a few smaller improvements.
> Release 0.12.5

- lib/src/container/store.rs
In the container flow we *always* create a merge commit nowadays, and we generally always expect multiple layers.
The `is_layered` here used to be meaningful when it counted non-ostree layers, but nowadays it's always true.
> lib: Remove `is_layered`

- lib/Cargo.toml
Prep for more (minor) API breaking changes.
> lib: Bump semver

- lib/src/container/encapsulate.rs
- lib/src/container/ocidir.rs
- lib/src/container/skopeo.rs
- lib/src/container/update_detachedmeta.rs
> container: Switch to cap-std when exporting to oci

- lib/Cargo.toml
This pairs with https://github.com/ostreedev/ostree/pull/3166/commits/f81b9fa1666c62a024d5ca0bbe876321f72529c7
> Release 0.13.2

- lib/Cargo.toml
A few improvements, most notably handling for zstd.
> Release 0.13.4

- lib/Cargo.toml
> Release 0.14.4

- lib/Cargo.toml
- lib/src/container/store.rs
- lib/src/container/update_detachedmeta.rs
- lib/src/integrationtest.rs
No major changes, just API cleanups.
> Update to ocidir 0.2

- lib/src/container/store.rs
rpm-ostree at least needs this.
> store: Add a public accessor for layer

- lib/Cargo.toml
> Release 0.15.2

- README.md
See https://github.com/containers/bootc/pull/875/
> README.md: Note merge
