- .github/workflows/rust.yml
So we have the latest libostree.
>  ci: Use fcos buildroot 

- .github/workflows/rust.yml
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- lib/src/tar/import.rs
- lib/tests/it/main.rs
This is a lot more efficient; before we were creating a thread
per object, etc.
> tar/import: use new writing APIs

- lib/src/container/export.rs
- lib/src/lib.rs
- lib/src/variant_utils.rs
Builds on/requires https://github.com/ostreedev/ostree-rs-ext/pull/16
Make variant_utils a public module
Getting things into gtk-rs would take a while before we can
depend on it, and perhaps we want to move in the direction of
the `gvariant` crate anyways.
For now let's just make this a public stable API so it can
be shared between here and rpm-ostree and e.g. ostree's test suite.
> Variant utils

- cli/src/main.rs
- lib/Cargo.toml
- lib/src/async_util.rs
- lib/src/container/import.rs
- lib/src/lib.rs
- lib/src/tar/import.rs
- lib/tests/it/main.rs
We're currently using the synchronous tar library, so we need to
do bridging.  This pushes the bridging down a layer, changing
our tar import API to be async.
Then things will be even clear if we switch to e.g.
https://crates.io/crates/tokio-tar
But we need https://github.com/vorot93/tokio-tar/pull/3
> Make tar import API async

- cli/Cargo.toml
- cli/src/main.rs
- lib/Cargo.toml
- lib/src/container/export.rs
- lib/src/container/import.rs
> Use tracing, not logging

- lib/Cargo.toml
- lib/src/async_util.rs
- lib/src/container/import.rs
- lib/src/container/skopeo.rs
Depends: https://github.com/ostreedev/ostree-rs-ext/pull/20 (mostly to avoid conflicts)
container: Use docker-archive: to stream image
It turns out that for whatever reasons (presumably mostly historical)
in skopeo, while `oci-archive:` is backed by just writing everything
to a tempdir and then tarring it up, the `docker-archive:` format
is actually streaming.
And it's *way* nicer and more efficient to stream.  Then the
last piece of this puzzle is that I realized we can use a named pipe
i.e. `mkfifo` to avoid having the containers/image stack crash
because it wants to invoke `realpath()` on the provided target.
By simply giving our pipe a name, it can do so (though it's
pointless) but this way we work with shipped versions of skopeo
and don't need to wait months for patches to propagate. …
> container: Use docker-archive: to stream image

- cli/src/main.rs
- lib/src/ima.rs
- lib/src/lib.rs
- lib/src/variant_utils.rs
This code is adapted from https://github.com/coreos/rpm-ostree/pull/2747
Overall, there's a lot of apparent synergy between ostree and IMA.
Both are file based.  IMA signatures cover file content and some
metadata.  The goal of EVM is also to cover security-relevant xattrs
(unlike e.g. fs-verity).
This initial code is known to generate bootable Fedora CoreOS
instances, but has not seen extensive testing beyond that.
> Add support for IMA signatures

- lib/Cargo.toml
These were parts of async skopeo that didn't pan out or aren't
necessary anymore.
> Remove some unused deps

- lib/src/container/mod.rs
It's extremely useful to be able to push images into the local
container storage.
> container: Also bind containers-storage

- lib/src/container/export.rs
- lib/src/container/oci.rs
It's really inefficient to do gzip only to have the destination
decompress again.
> container/export: When writing to `containers-storage:`, don't compress

- cli/Cargo.toml
- lib/Cargo.toml
Mainly adds `container export containers-storage:` which is
going to be very useful for things like CI tests, and also helps
complete the picture of bidirectional mapping between ostree
and containers.
> Release 0.1.2

- lib/src/variant_utils.rs
A lot of rpm-ostree code parses `glib::VariantDict` with strings
and booleans.
> variant_utils: Add VariantDictExt

- lib/Cargo.toml
It's going to be more tuned for e.g. target CPU than the Rust
version, and we already link to it in process.
> lib: Link to zlib

- lib/Cargo.toml
At some point I think rust-analyzer did automatic imports and
that made things an inconsistent mess.  I find the "inline"
declarations *much* more readable.
> lib/Cargo.toml: Clean up declarations

- lib/src/container/oci.rs
oci: Add crate name/version in history
For debugging purposes.
---
oci: Generate correct uncompressed hash
I broke this in a refactoring, turns out `docker` checks it
but `podman` doesn't (which seems to clearly be a bug).
Reported on chat by someone trying out running
via `docker`.
---
> oci: Generate correct uncompressed hash

- .github/workflows/rust.yml
- lib/src/cli.rs
- lib/src/container/oci.rs
ci: Use latest buildroot, drop ostree override
The latest official buildroot has what we need.
---
Run `cargo fmt` and add ci check
---
> ci fixes and cargo fmt

- cli/Cargo.toml
- lib/Cargo.toml
Breaking changes:
- glib 0.14
- Removed most now unnecessary bits from `variant_utils`
> Release 0.2.0

- lib/Cargo.toml
- lib/src/cli.rs
This sorts the dependencies in 'lib' manifest, updates them all to
the latest versions, and massages code for all changed APIs.
> cargo/lib: update all dependencies

- lib/Cargo.toml
To pull in the updated deps, to avoid having lots more to vendor
for rpm-ostree.
> Release 0.2.1

- lib/src/container/oci.rs
I think the OCI arch matches the kernel architecture on other
platforms.
> oci: Pass through other architectures

- cli/Cargo.toml
- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/container/export.rs
- lib/src/diff.rs
- lib/src/ima.rs
- lib/src/tar/export.rs
- lib/src/tar/import.rs
- lib/src/variant_utils.rs
- lib/tests/it/main.rs
By using the re-export, we avoid needing to keep a version lock
between glib and glib-sys in our main crate.  This helps
dependabot, etc.
> Use gio via `ostree::gio`

- lib/Cargo.toml
- lib/src/lib.rs
I am totally cargo culting the bits from ostree-rs without understanding
them.  I guess this somehow avoids having the dependencies installed
in the random docs.rs build container?
> Try to fix the docs.rs build

- cli/Cargo.toml
- lib/src/lib.rs
- lib/tests/it/main.rs
This is the equivalent of https://github.com/ostreedev/ostree-rs/pull/13/commits/a1e5bc3f320a28b3a7fd80b9a7f6b0ff76540a23
This allows our users to avoid adding explicit dependencies on
those libraries, because in practice e.g. `ostree` and `gio`
must be versioned together.
> Re-export our dependencies (`ostree`, `gio`, `glib`) and add a prelude

- lib/Cargo.toml
```
Colin Walters (8):
oci: Pass through other architectures
Use glib-sys via re-exported glib::ffi
Use `glib` via re-export from `gio`
ima: Use new GVariant code, drop unsafe
Use gio via `ostree::gio`
Try to fix the docs.rs build
Re-export our dependencies (`ostree`, `gio`, `glib`) and add a prelude
Release 0.2.2
Luca BRUNO (1):
cargo: fix repository location
```
> Release 0.2.2

- lib/src/lib.rs
- lib/src/tar/export.rs
- lib/src/tar/import.rs
- lib/tests/it/main.rs
There were multiple bugs here.
Prep for implementing signing:
https://github.com/ostreedev/ostree-rs-ext/issues/2
> tar: Correctly pass import/export commit metadata

- lib/Cargo.toml
- lib/src/container/import.rs
- lib/src/tar/import.rs
I saw this in https://www.reddit.com/r/rust/comments/pkr9aa/is_the_crate_dependency_becoming_a_problem/
That said it turns out `glib` is depending on `futures-executor` right
now too.
> lib: Only depend on futures-util

- lib/Cargo.toml
- lib/src/lib.rs
- lib/src/tar/export.rs
lib: Bump to 0.3
We're going to make some semver-incompatible changes.
---
lib: Bump to ostree 0.9
We can drop our FFI workaround.
---
> Prep release 0.3.0

- lib/src/tar/import.rs
lib/tar/import: Move more logic into Importer struct
Let's keep the code inside an anonymous closure smaller.
---
lib/tar/import: Remove lifetime from Importer
It's really easier to just bump the gobject refcount; not
worth carrying a lifetime for this.
---
lib/tar/import: Explicitly parse commit object first
Prep for signing.  Rather than maintaining a state machine,
just explicitly read the first object and validate it as
a commit.
This way we can later also read the commitmeta in the same
way and validate both before writing them to the repo.
---
> Tar cleanup 2

- lib/src/container/export.rs
- lib/src/container/import.rs
- lib/src/container/mod.rs
- lib/src/container/skopeo.rs
- lib/tests/it/main.rs
lib/container: Introduce OstreeImageReference with SignatureSource
I'm trying to put my foot down and say that *by default* booting
and updating an operating system should require a cryptographic
signature from the vendor as implemented by e.g. ostree (GPG or
"signapi" which can do simple ed25519+libsodium signatures).
Other signature mechanisms are possible and the containers/image
ecosystem supports signatures, but they are not widely deployed.
In order to implement ostree-based GPG/signapi verification, we
need the configuration for an ostree remote.  Hence, we support
`ostree-remote-image:$remotename:$containerref`.  For example,
`ostree-remote-image:fedora:registry:quay.io/coreos/fedora-coreos:stable`.
Having a canonical stringified representation of this will
allow using it on …
> lib/container: Introduce OstreeImageReference

- lib/src/cli.rs
- lib/src/container/mod.rs
- lib/src/tar/mod.rs
lib/{tar,container}: Add a lot more module level docs
This overlaps with the `README.md` but I plan to tweak things
in a bit to have that link to `docs.rs`.
---
lib/cli: Fix link to clap
Because we're not importing `clap` directly but only indirectly via
`structopt`, we got a warning from `cargo doc`.
---
> tar+container rustdoc

- lib/src/container/import.rs
Right now a failure during skopeo pull when ostree-remote verification
is enabled actually manifests as "no commit found".
Prioritize emitting a skopeo error, because a failure there probably
has the real error.
> container/import: Check skopeo errors first

- lib/Cargo.toml
I plan to make some API changes in the `container` module at least.
> lib: Bump to 0.4.0-alpha.0

- lib/src/container/export.rs
- lib/src/container/mod.rs
- lib/tests/it/main.rs
Per `man containers-transports`, transports like `oci-archive:`
don't support digests, and even major ones like `containers-storage:`
and `docker://` don't quite handle them in the same way.
For now, avoid trying to mutate transport references.  It's just
the push path that was doing this; instead just return the digest
as a string.  We will likely need to special case `docker://` but
that can come later.
> lib/container: Remove with_digest() method

- lib/tests/it/main.rs
Just reading the test code and I want to do this in more tests.
> tests: Strengthen error check for empty archive

- lib/src/container/import.rs
Rather than passing the FIFO stream ownership into and back out
of the parser, just pass an `&mut` reference, and then
explicitly drain it in the worker thread.
This motivates then cleaning up our "worker" futures.  Add some
comments too.
Prep for future work.
---
> lib/container: Explicitly drain stream

- lib/tests/it/main.rs
tests: Add srcrepo to Fixture
Since most tests want to operate on a src and dest repo,
move the creation of the srcrepo into `Fixture`.
General cleanup and prep for future work.
---
tests: Drop redundant destrepo creation
It's been in `Fixture` for a while.
---
> Test fixture cleanup

- lib/src/cmdext.rs
- lib/src/ima.rs
- lib/src/lib.rs
- lib/src/tar/import.rs
- lib/src/tar/mod.rs
- lib/src/tar/write.rs
- lib/tests/it/main.rs
APIs to write a tarball stream into an OSTree commit.
This functionality already exists in libostree mostly,
this API adds a higher level, more ergonomic Rust frontend
to it.
In the future, this may also evolve into parsing the tar
stream in Rust, not in C.
Prep for container derivation.
> lib/tar: Add new `write` module

- .github/workflows/rust.yml
- ci/installdeps.sh
- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/container/imageproxy.rs
- lib/src/container/import.rs
- lib/src/container/mod.rs
- lib/src/container/skopeo.rs
https://github.com/cgwalters/container-image-proxy
is prototype code to expose containers/image via a HTTP API
suitable for use in non-Go programs.
This has many advantages over us forking skopeo; the key one being
on-demand layer fetching.
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/18
> Fetch via container-image-proxy

- lib/src/container/imageproxy.rs
imageproxy: Add context to failure to spawn
Since missing the binary is probably going to be common.
---
imageproxy: Add some docstrings
On general principle.
---
> Layered import followups

- lib/Cargo.toml
- lib/src/async_util.rs
- lib/src/container/import.rs
- lib/src/tar/import.rs
lib/container: Use pin-project for ProgressReader
I recently read through https://fasterthanli.me/articles/pin-and-suffering
and realized the use of pin-project is what we need here.
This avoids us need an `Unpin` bound which is nicer.
I also switched to avoid mutating our own structure (if progress
receiver disconnects we just keep trying to send) because I was
fighting `Pin` + mutability.
---
lib: Clean up AsyncRead → Read bridge
I have now realized why so many APIs in std and tokio etc. return
named but generic structures.  It's because it helps ensure that things like
`Send` bounds are automatically propagated as needed.
If instead one wraps it behind a generic function, then all bounds need to
be specified on the return value (so you'd need one for `_send` types and
one for non-send …
> lib/container: Use pin-project for ProgressReader

- lib/src/tar/write.rs
- lib/tests/it/main.rs
We need this on general principle, because while ostree tries
to support both `/etc` and `/usr/etc`, in practice rpm-ostree
effectively requires ostree commits to have `/usr/etc`.
> lib/tar/write: Translate /etc → /usr/etc by default

- lib/Cargo.toml
This is dealt with in a newer nix but we need to match
what is locked in rpm-ostree right now.  See
https://github.com/nix-rust/nix/commit/5495bbce52d3541f90d13e692a1cef34e186e100
---
> lib: Lower bitflags requirement to just "1"

- lib/src/lib.rs
- lib/src/tokio_util.rs
This takes the code from https://github.com/coreos/rpm-ostree/blob/d6ed262f83b33e7fd454699b96661ba323d04128/rust/src/utils.rs#L163
which makes more sense here because:
- We depend on both glib and tokio and the code isn't rpm-ostree specific
- We will want to use this internally to ensure our worker threads
get cancelled.
> Add tokio_util module

- lib/src/container/oci.rs
It's generally useful.  Prep for later patches.
> oci: Add `#[derive(Clone, PartialEq, Eq)]`

- lib/src/container/imageproxy.rs
- lib/src/container/import.rs
> lib: Fix some rustdoc warnings

- lib/Cargo.toml
- lib/src/lib.rs
- lib/src/refescape.rs
Prep for work on the new container module, where we want to store
container image references (e.g. `docker://quay.io/coreos/fedora`)
as ostree refs.  Several bits of that are not valid in ostree refs,
such as the `:` or the double `//` (which would be an empty filesystem path).
This escaping scheme uses `_` in a similar way as a `\` character is
used in other syntax.  For example, `:` is `_3A_` (hexadecimal).
`//` is escaped as `/_2F_` (i.e. the second `/` is escaped).
> Add new refescape module

- lib/src/async_util.rs
- lib/src/tar/write.rs
- lib/tests/it/main.rs
Rather than trying to extend the ostree C code to support
arbitrary transformations, let's do pre-parsing here in safe Rust.
We keep the `/etc` → `/usr/etc` bits, but we also just completely
drop everything not in `/usr` now.
As noted in the comment, this pre-validation will hopefully also
catch any corrupt tarballs that might be exploitable in the C libarchive
codebase.
> lib/tar: Pre-filter tar archive in Rust

- lib/src/container/oci.rs
container/oci: Add config to Manifest
It's required, and we need it to compute the "ImageID".
xref https://github.com/ostreedev/ostree-rs-ext/issues/115
---
container/oci: Use our Manifest struct when writing
This way we get type safety, we're testing the API etc.
---
> container/oci: Add config to Manifest + container/oci: Use our Manifest struct when writing

- lib/src/cli.rs
- lib/src/container/encapsulate.rs
- lib/src/container/mod.rs
- lib/src/container/store.rs
- lib/src/container/unencapsulate.rs
- lib/tests/it/main.rs
Previously in https://github.com/ostreedev/ostree-rs-ext/pull/113
we changed the CLI entrypoints with this rationale:
> Since we're moving towards more "native" support for container
> images, we need to very clearly differentiate between the code
> that currently uses the terms "import" and "export" which are
> somewhat ambiguous.
To elaborate, the term "import" is ambiguous with respect to our
container "store" path, which generates a new ostree commit and
operates on arbitrary container images.
Let's take the next step now and rename the modules too.
> lib/container: Use "encapsulate" terminology for module names too

- cli/src/main.rs
- lib/src/container/mod.rs
- lib/src/tar/mod.rs
We had duplicate versions of these inside the `mod.rs`; the
versions in the top level `lib.rs` are all that are needed.
However, because the cli is a separate unit, copy them there too.
Not that there's actually anything actually *in* the cli `main.rs`,
but it's a good best practice in case the code does grow for some
reason, or it gets cargo culted elsewhere.
> Clean up `deny/forbid` bits

- lib/src/cli.rs
- lib/src/container/deploy.rs
- lib/src/container/store.rs
- lib/tests/it/main.rs
containers: Expose a state struct with base commit and layering state
This is actually quite analogous to what rpm-ostree does internally;
a lot of the internals there distinguish "base" versus "layered"
commits, and this is very similar.
Here, when we import a non-layered image, we can mostly
ignore the merge commit since all it has is the image manifest.
The base image layer ref *is* the encapsulated ostree commit with
all the metadata injected by (rpm-)ostree in the non-layered case.
Add an API which exposes this as a struct, and also return it
from the importer's `AlreadyPresent` case.
---
container: Change import result case to contain state struct
Notably, this also stops exposing the ostree ref for the merge commit,
which I think is a good idea in general since it should be thought …
> container: Rework API and model around "base commit" and "merge commit"

- lib/Cargo.toml
- lib/src/container/store.rs
- lib/src/container/unencapsulate.rs
Add some more tracing in container path
Seeing a hang in upgrades in rpm-ostree, this may help debug.
---
container: Bump to containers-image-proxy 0.2
This requires threading `mut` around more.  Motivated by
improved logging/debugging.
---
> Tracing and containers-image-proxy 0.2

- lib/src/cli.rs
- lib/src/container/deploy.rs
- lib/src/container/store.rs
- lib/tests/it/main.rs
The import path was previously providing the data about filtered-out
content (e.g. files in `/var`) "out of band" as part of the import
return value.  But this means that unless that data is e.g. logged
it ends up being lost.
Since the amount of data is bounded, let's instead add it as metadata
to the merge commit.
Then this lets us make a nice cleanup of entirely dropping the
`CompletedImport` struct in favor of the `LayeredImageState` that
we use in various places.
Now it's possible for something like `rpm-ostree status` to also
reliably show how many files were filtered out of each layer.
> container/store: Write filter data to commitmeta, clean up API

- lib/src/cli.rs
- lib/src/container/encapsulate.rs
- lib/tests/it/main.rs
This exposes the ability to disable compression, which is mostly
only useful for the internal flow that pushes to containers/storage
where we don't want compression.
But the main goal here is to pave the way for adding a `bool chunking`.
> container: Add options struct for encapsulation

- Cargo.toml
> `Cargo.toml`: Add build tweaks from rpm-ostree

- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/container/deploy.rs
- lib/src/container/store.rs
- lib/src/container/unencapsulate.rs
- lib/tests/it/main.rs
Bump to containers-image-proxy 0.3
---
lib/container: Drop unnecessary `mut` for proxy
The proxy has gone back to a shared borrow with internal locking.
---
lib: Expose proxy configuration as public API
We will need to support basically all options that the proxy
does, such as disabling TLS, separate authfile etc.
Rather than write a new type, just re-export it.
Thread the new options struct through the store and deploy APIs.
---
cli: Expose current container proxy opts as CLI flags
We want this for the same reason they exist in skopeo
around non-default authfiles, etc.
The chain here is pretty amazing:
- containers/image internal Go API
- skopeo CLI flags
- containers/containers-image-proxy Rust API
- ostreedev/ostree-rs-ext Rust API
- ostreedev/ostree-rs-ext CLI code
- rpm-ostree CLI …
> Bump to containers-image-proxy 0.3, add proxy config as API and CLI

- lib/src/cli.rs
This way it's not a breaking change to add a new member to the
struct.
> cli: Use `..Default::default()` for proxy options

- lib/src/tar/import.rs
The `entry::header().link_name()` path doesn't support long links,
and this is a documented foot-gun.  Use `entry::link_name()` instead.
Needed for e.g.
`/ostree/repo/objects/87/c8834da3bad596352375ff413bca064584f184bdd6ba1764293d137249e168.file -> ../../../../usr/lib64/qt5/plugins/wayland-graphics-integration-server/libqt-wayland-compositor-xcomposite-egl.so`.
> tar/import: Use the correct API to read link name

- lib/src/tar/import.rs
- lib/tests/it/main.rs
This mirrors the logic in `ostree_repo_pull()` - before
we write the commit object, we want to mark it as partial so
the core knows objects are still being written.  And after the
transaction, undo that marker.
Motivated by supporting "chunked" containers (split tar) where
this partial state will be more obvious.
> tar/import: Write commitpartial state

- lib/src/tar/import.rs
tar/import: Remove unnecessary `abort_transaction()`
This is dead code since b7ba07556c8c54a719f47d9a8f1ef47b5b7a0e4b
when we switched to `auto_transaction()`.
---
tar/import: Move directory filtering into filter function
It's cleaner if our `filter_entry` function does most of the
work here instead of having half of the filtering in a closure.
---
tar/import: Move txn outside of `Importer`
This is prep for split tar imports, where we'll reuse distinct
calls to the importer across a single transaction.
---
> A few small patches for `tar/import`

- lib/src/tar/export.rs
Currently it looks like `sysroot/ostree/repo/objects/0xf5`
when it should obviously be
`sysroot/ostree/repo/objects/f5`.
Reported by @giuseppe
> tar/export: Fix numeric export for objects directories

- lib/src/tar/export.rs
- lib/tests/it/main.rs
tar: Factor out helper to write default directory
Prep for ensuring we create all parent dirs to aid containers/storage.
---
tar/export: Create all parent directories too
This is really the standard/expected thing to do.  The current
containers/storage stack handles this, but the experimental chunked
back end did not until
https://github.com/containers/storage/pull/1072/commits/501611fd510f3406aab3acf25b18545d321ebb79
---
>  tar/export: Create all parent directories too

- lib/src/container/encapsulate.rs
Since that's what's in CentOS8 at the moment.  The `From` impl
on `HashMap` for tuples is too new.
> container/encapsulate: Be compatible with Rust 1.54

- .github/workflows/rust.yml
This adds a new CI jobs to make sure the code is building fine under
a given MSRV. It mostly helps making sure we stay compatible with
system toolchains shipped by distros (e.g. RHEL8).
This keeps using system dependencies from FCOS buildroot (notably,
a fresh ostree), but it drop the installed toolchain in favor
of a CI-pinned one.
> ci: add GH workflow for Minimum Supported Rust Version (MSRV)

- .github/workflows/rust.yml
- lib/src/cli.rs
- lib/src/tar/export.rs
This fixes the following warnings highlighted by clippy:
* https://rust-lang.github.io/rust-clippy/master/index.html#from_over_into
* https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
It also adds a new CI job dedicated to linting, which includes steps for
rustfmt and clippy.
> ci: add GH workflow for linting 

- lib/Cargo.toml
- lib/src/container/store.rs
- lib/src/container/unencapsulate.rs
- lib/src/lib.rs
- lib/src/tar/write.rs
Add some missing `#[derive(Debug)]`
Hit this when I wanted to add `dbg!`.
---
Drop ununused `bytes` dependency
We aren't doing HTTP directly anymore.
---
lib: Also add `unreachable_pub` to opted-in lint
And link to the list.
I plan to cargo cult this elsewhere.
---
> Add some missing `#[derive(Debug)]`

- lib/Cargo.toml
This refreshes `nix` and `phf` dependencies, making sure everything
is up-to-date.
> lib/cargo: update stale dependencies

- lib/Cargo.toml
- lib/src/cli.rs
Exposes the corresponding options from containers-image-proxy and
skopeo
Also changes authfile type from String to PathBuf for consistency
Helps https://github.com/ostreedev/ostree-rs-ext/issues/121
Depends https://github.com/containers/containers-image-proxy-rs/pull/22
> cli: Expose certificate_directory

- lib/src/container/deploy.rs
- lib/src/container/store.rs
- lib/src/container/unencapsulate.rs
I was seeing this in a `cosa build`:
```
+ rpm-ostree ex-container image deploy --imgref ostree-unverified-image:oci-archive:/var/srv/walters/builds/rhcos-master/builds/410.84.202112092014-0-1/x86_64/rhcos-410.84.202112092014-0-ostree.x86_64.ociarchive --stateroot rhcos --sysroot /tmp/rootfs --karg=random.trust_cpu=on --karg=console=tty0 --karg=console=ttyS0,115200n8 --karg=ignition.platform.id=qemu '--karg=$ignition_firstboot'
error: Performing deployment: remote error: write |1: broken pipe
```
which is not useful.
This is really a brutal hack around the fact that an error can occur
on either our side or in the proxy.  But if an error occurs on our
side, then we will close the pipe, which will *also* cause the proxy
to error out.
What we really want is for the proxy to tell us when it …
>  containers: Better handle errors from worker and/or driver

- lib/src/container/encapsulate.rs
- lib/src/container/ociwriter.rs
Prep for https://github.com/ostreedev/ostree-rs-ext/issues/69
where we'll split up the input ostree commit into content-addressed
blobs.
We want to inject something useful into the the `history` in the
config git that describes each chunk, so add support for that
into our OCI writer.
Change the default description for the (currently single) layer
to include the commit subject, if present; otherwise the
commit hash.
The description of the layer shouldn't change as this tool changes,
just as the input changes.
(Side note; today rpm-ostree isn't adding a subject description,
but hey, maybe someone else is)
> container: Add history struct to oci writing, tweak history description

- lib/src/container/mod.rs
This fixes a wrong and colliding error prefix, possibly coming
from a copy-paste mistake.
> lib/container: fix error prefix for invalid ostree imgref scheme

- lib/src/container/store.rs
- lib/src/container/unencapsulate.rs
This came out of some prep work on
https://github.com/ostreedev/ostree-rs-ext/issues/69
Right now it's confusing, the layering code ended up re-implementing
the "fetch and unpack tarball" logic from the unencapsulation path
unnecessarily.
I think it's much clearer if the layering path just calls down
into the unencapsulation path first.
Among other things this will also ensure we're honoring the image
verification string.
> container: Make layering more directly re-use unencapsulation

- lib/Cargo.toml
- lib/src/tar/export.rs
Use new `append_link()` API to handle long symlinks
I hit this when exporting Fedora Silverblue, there are some
long symlinks in there.
Depends: https://github.com/alexcrichton/tar-rs/pull/273
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/162
---
tar/export: Write symlink targets literally
Requires: https://github.com/alexcrichton/tar-rs/pull/274
And I'll just copy/paste the commit message from there, lightly edited:
In https://github.com/ostreedev/ostree we generate a cryptographic
checksum over files and symlinks, and directories.
ostree does not currently perform any canonicalization on symlinks;
we'll respect and honor whatever bytes we're provided as input,
and replicate that on the target.
We're using the Rust tar crate to do tar serialization,
which has so far worked …
> Handle long and denormal symlinks

- lib/Cargo.toml
- lib/src/tar/export.rs
- lib/tests/it/main.rs
I hit on the fact that we were missing `/tmp` in the exported
container, and this is because we were actually missing writing
directory entries.  It only works because container runtimes
will auto-create parent directories.
But we clearly want to reflect the intended uid/gid/mode in the
tar stream too, and we definitely want empty toplevel dirs like
`/tmp`.
The simple fix of emitting them in our current flow actually fails
when trying to import into `containers/storage`, complaining about
duplicate entries.
And this is because the simple fix ends up writing a `sysroot` entry
with two different modes (0755 and 0700).  One or the other needs
to win, let's just have it be 0755 for now, though it doesn't really
matter for this.
So to really make this work, rework the flow so that the tar …
> tar: Write directory hierarchy correctly

- lib/src/container_utils.rs
- lib/src/lib.rs
This isn't going to be perfect, but it will serve for now.
We will need it in both this codebase as well as rpm-ostree, so let's
make it a public API.
> Add a container_utils module with API to detect containerization

- .github/workflows/rust.yml
- ci/integration.sh
- lib/src/cli.rs
- lib/src/integrationtest.rs
- lib/src/lib.rs
The core idea here is that we take our built binary and inject
it into a fcos container image, where we can do further testing.
For now just to prove this out I've added an internal testutils
command.
(I think I'd like to write more tests in Rust, but to do that
correctly we also want a `bin-unit-tests` feature like rpm-ostree
has, which can come later)
> Add new integration testing flow

- lib/src/tar/export.rs
This fixes an important regression from https://github.com/ostreedev/ostree-rs-ext/pull/186
Basically we have now a really ugly hack around `/sysroot` that
wasn't caught by the unit tests here because the OS content doesn't
have it.  I'm going to do a followup where we extend our integration
testing more here.
But anyways, we still need to emit the dirmeta object for `/sysroot`,
even if not its contents.  (Actually, it *should* be empty in an
ostree commit, hmm probably ostree should enforce that)
> tar/export: Do emit dirmeta for `/sysroot`

- lib/src/tar/export.rs
I was working on this area of code for a previous PR, and I almost
made a refactoring that shared the `hexbuf`.  I think the stack
allocation here was a premature optimization.  Let's just heap
allocate - modern allocators are fast with thread-local
storage and caches etc.  The C side allocates a ton anyways.
However there is an optimization we can make here - by passing
ownership of the checksum string into the recursive dirtree walk,
we can drop it before recursing.   Now there's only one heap
allocation there instead of it being O(depth).
> tar/export: Do checksum → string a bit smarter

- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/lib.rs
Most of our current testing is via an integration test,
which I designed after reading
https://matklad.github.io/2021/02/27/delete-cargo-integration-tests.html
However, I then wanted to use our internal OCI build tooling from the
integration test, which is blocked (by design) from seeing non-`pub`
things.
I initially tried doing:
```
#[cfg(test)]
pub fn do_oci_stuff(...)
```
but that didn't work.  (Perhaps it should?)
After some searching I came across this gem:
https://github.com/rust-lang/cargo/issues/2911#issuecomment-749580481
Which, looks an amazing hack.  But it works.
The *big* downside of this is that now in order to properly test
building without the integration test feature, one must do so
via a fully distinct crate.
> Use a self-enabled `integration-testing-api` feature

- lib/src/tar/export.rs
Fixes https://discussion.fedoraproject.org/t/rebasing-from-container-registry/35356
(This needs unit tests I know, but right now our content set is
a manually-generated fixed tarball, and I have some patches in the
work to improve the test suite)
> tar/export: Correctly set size and entry type for denormal links

- lib/src/cli.rs
- lib/src/container/encapsulate.rs
- lib/src/container_utils.rs
- lib/src/tar/export.rs
- lib/tests/it/main.rs
It turns out adding `/sysroot/ostree/repo/config` into the export
stream broke compat with older code.  Now in theory this is all
experimental and changeable, but it breaks the FCOS upgrade testing
because the export format there is "production" for some values of
production.
And for our own sanity, it's helpful to be compatible.
And add format versioning into the tar export code, and default to v0
where we put the config into `/sysroot/config` where it will be ignored
by older ostree.
This in particular should allow us to update rpm-ostree to the
latest ostree-ext in https://github.com/coreos/rpm-ostree/pull/3285
> tar: Move repo config into `/sysroot/config` by default for backcompat

- lib/src/container_utils.rs
This came up in https://github.com/coreos/rpm-ostree/pull/3297
Most of our checks are going to be for this.
> lib/container_utils: Add helper `is_ostree_contaner()`

- lib/src/ima.rs
Part of investigating using rustix instead of nix.
> ima: Use std's `last_os_error()` instead of nix

- lib/src/cli.rs
This fixes the above warning:
```
cargo build
Compiling ostree-ext v0.5.1 (/var/home/jmarrero/Development/github/ostreedev/ostree-rs-ext/lib)
warning: field is never read: `repo`
--> lib/src/cli.rs:31:5
|
31 |     repo: String,
|     ^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: field is never read: `ostree_ref`
--> lib/src/cli.rs:34:5
|
34 |     ostree_ref: String,
|     ^^^^^^^^^^^^^^^^^^
warning: field is never read: `oci_dir`
--> lib/src/cli.rs:37:5
|
37 |     oci_dir: String,
|     ^^^^^^^^^^^^^^^
warning: `ostree-ext` (lib) generated 3 warnings
```
Also making the struct and fields pub will fix it but since the other struct in the module are not pub I am just adding the underscore here.
> lib/src/cli: Update BuildOpts fields to denote they might not be read

- lib/Cargo.toml
- lib/src/container/store.rs
- lib/tests/it/main.rs
We cut a new version upstream, let's switch back to crate dependencies.
> lib: Switch to released containers-image-proxy version

- lib/Cargo.toml
Switch to published ostree crate
In prep for releasing a new version.
---
Release 0.6.0
Semver bump because of various API changes.
---
> Release 0.6.0

- lib/src/container/encapsulate.rs
Came across this in a refactoring.  Glob imports should be used
sparingly.
> container: Drop `use super::*`

- lib/src/container/store.rs
- lib/src/tar/import.rs
- lib/src/tokio_util.rs
I think this is nicer than having `??` which still looks odd to me,
and we can also drop a `map(anyhow::Error::msg)` in once place too.
Prep for further work.
> Add a helper to flatten `Result<Result<T>>` with tokio_util

- lib/src/container/ocidir.rs
Turns out that `podman history` segfaults if this is missing.
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/211
> ocidir: Add creation time into history

- ci/integration.sh
- lib/src/cli.rs
- lib/src/container/mod.rs
- lib/src/container/store.rs
- lib/src/container_utils.rs
- lib/src/globals.rs
- lib/src/integrationtest.rs
- lib/src/lib.rs
This is related to https://github.com/ostreedev/ostree-rs-ext/issues/121
as well as https://github.com/containers/containers-image-proxy-rs/pull/8
etc.
The CLI code here supports `--authfile`.  However, passing it on
the CLI each time for production use cases pushes complexity to
users.
Add support for global persistent and runtime config files in
`/etc/ostree/auth.json` and `/run/ostree/auth.json`.
Change the default constructor for image pulls to use that by default.
Note that the CLI options override the config defaults.
While we're here, also add `--auth-anonymous` to the CLI, which is
needed to ensure we don't use a config file if present.
> container: Support `/etc/ostree/auth.json` and in `/run` too

- lib/src/container/encapsulate.rs
- lib/src/container/store.rs
- lib/src/ima.rs
- lib/src/tar/export.rs
- lib/tests/it/main.rs
I added this back in
https://github.com/ostreedev/ostree-rs/pull/35/commits/f8aa658d17af9c13702a20ea8d4030cc34121bc8
and only recently remembered about it when modifying some other
code.
We need some sort of automatic reminder system for "remember
to use this new API from your dependency".
> Switch to new `require_rev` API

- lib/src/commit.rs
- lib/src/container_utils.rs
- lib/src/integrationtest.rs
utils: Add an API to require being in an ostree container
Most of our callers actually want this.
---
lib/commit: Use `require_ostree_container()` API
---
> Add and use an API to require being in an ostree container

- lib/Cargo.toml
- lib/src/container/encapsulate.rs
- lib/src/container/ocidir.rs
- lib/src/integrationtest.rs
Now that https://github.com/containers/oci-spec-rs/pull/90/commits/6e65562e3d70b66656598e6a567dc71e80dd0f56
landed, we can just depend on it and not have a hardcoded
architecture mapping here.
> Use new correct `impl Default` for oci bits

- lib/tests/it/main.rs
I'm realizing the default of having `bash!` use `set +x` by default
was perhaps a mistake.  But this at least makes the test output
more legible, if not perfect.
> tests: Quiet output of most shell commands

- lib/src/tar/export.rs
- lib/tests/it/main.rs
This enhances the logic for tar-exporting, so that
libostree can more easily operate on the repo.
It also contains a couple of bugfixes, and an overall unit-test
for the repo skeleton.
/cc @cgwalters
> tar/export: add additional mandatory ostree repo directories

- lib/src/tar/export.rs
- lib/src/tar/import.rs
- lib/tests/it/main.rs
This fixes the tar exporting logic to avoid leaking filetype bits
into mode field. The tar header already has a distinct field to
identify entry type, thus mode bits should only convey permissions.
Ref: https://github.com/ostreedev/ostree-rs-ext/pull/217#discussion_r791942496
> tar/export: fix mode bits in tar archive

- lib/src/container/mod.rs
- lib/src/container/ocidir.rs
We have this trick of compiling ourself with integration testing
enabled, which uses a lot of the code here.   See the
`ostree-ext = { path = ".", features = ["internal-testing-api"] }`
bit in Cargo.toml.
But that isn't turned on for other crates that use this, and correctly gating all
of it is a little tedious.  So let's just use the big hammer for now to
quiet the dead code warnings.
> lib/container: Quiet dead code warnings for `ocidir`

- lib/Cargo.toml
Fixes a backwards incompatible change in the (now yanked) 0.6.1.
> Release 0.6.2

- lib/Cargo.toml
- lib/src/container/ocidir.rs
Sadly RHEL8's glib is too old for this.  Switch to using chrono.
> ocidir: Use `chrono`, not `glib` for time formatting

- lib/Cargo.toml
Nothing critical, just the cap-std bump and the chrono fix;
I particularly want the latter for the next rpm-ostree.
> Release 0.6.3

- lib/src/cli.rs
- lib/src/container/encapsulate.rs
- lib/tests/it/main.rs
For https://github.com/coreos/coreos-assembler/issues/2685
we want to copy e.g. `rpmostree.input-hash` into the container image.
Extend the `ExportOpts` struct to support this, and also expose
it via the CLI, e.g.
`ostree container encapsulate --copymeta=rpmostree.input-hash ...`.
And while I was thinking about this...we should by default copy
some core ostree keys, such as `ostree.bootable` and `ostree.linux`
since they are key pieces of metadata.
> container/encapsulate: Support copying commit metadata keys

- lib/Cargo.toml
- lib/src/container/encapsulate.rs
- lib/tests/it/main.rs
lib: Bump ostree crate, enable `cap-std-apis`
This way we can start making use of cap-std more.
---
container/encapsulate: Honor `ostree.container-cmd`
Builds on https://github.com/ostreedev/ostree-rs/pull/47/commits/6d3a69cc43214a77085e98f062f9f624c4ea25db
Part of https://github.com/coreos/coreos-assembler/issues/2685
---
> container/encapsulate: Honor `ostree.container-cmd`

- lib/src/tar/export.rs
This makes sure that xattrs content is always exported in v1 format,
even the empty attributes set. Previous behaviour is retained for v0,
for compatibility.
> tar/export: export empty xattrs in v1 format

- lib/tests/it/fixture.rs
- lib/tests/it/main.rs
OK so...buckle up.  I've been working on this ostree stuff for
like 10 years now it turns out that I still stuck at writing
the test suites.
When I generated the hardcoded `exampleos-v0.tar.zstd`, I apparently
included SELinux labels (I don't think intentionally).
But I didn't when generating `exampleos-v1.tar`!
I was trying to test an upgrade path around xattrs and hit a bug there
code, and it took me a while to understand it was because the second
update didn't have them!
The time it took to debug this was greatly extended by me reading
`man tar`, and thinking that `tar -tf -v --xattrs` would print any SELinux
label.  But no - SELinux is *special cased* in tar - even though
it's an extended attribute, in order to see any embedded labels
in the tarball one needs to use `tar -tf -v …
> tests: Factor out test fixture as a separate module

- lib/src/tar/import.rs
This bug may have existed before, but basically we need
to handle the case where an object already exists in the repo;
we were erroring out in this case because we retained the queued
xattrs entry.
> tar/import: Don't crash on extant object

- lib/Cargo.toml
- lib/tests/it/fixture.rs
- lib/tests/it/main.rs
Prep for further work.
I just cut a new release of `sh-inline` - we now have a `cap-std-ext`
feature which lets us use `bash_in!` which takes a reference
to a directory fd.
Also of note, passed variables are now shell-like `${foo}` instead
of substituted.
This is significantly less fragile than having our script do a
`cd` at the top.
This also starts us down the path to porting the framework to use
`cap-std`, e.g. the fixture uses the new `open_at_dir()` API from
https://github.com/ostreedev/ostree-rs/commit/e1fa1da4cafad874a6e58fbea326ded5255e0cdd
> testsuite: Port to `sh-inline` 0.2

- lib/tests/it/fixture.rs
- lib/tests/it/main.rs
tests: Split off fixture base prep from repo initialization
---
tests: Port to use more `bash_in!` and drop absolute paths
---
tests: Drop src absolute path
This patch series is staring to feel like spraying Windex on a dirty
window, and watching it get cleaner.
---
tests: Use cap-std in more places
---
tests: Move initial commit into fixture
---
> A few more test suite patches

- lib/tests/it/fixture.rs
- lib/tests/it/main.rs
tests: Move tar export as method on fixture
It's cleaner.
---
tests: Drop the usage of indoc for commit
It's mostly just obscuring things.
---
> Two more small test suite patches

- lib/tests/it/fixture.rs
- lib/tests/it/main.rs
Depends: https://github.com/ostreedev/ostree-rs-ext/pull/248
---
tests: Add much beefed up alternative path for test framework
The main thing I want to get away from is hardcoded tarball fixtures.
I do want the commit digests we write to be reproducible, and
I also want the unit tests to work on a non-SELinux system.
This patch adds an alternative flow to the text fixture via `new_v1()`
that uses the native ostree APIs to write and generate commits.  We
mock up the SELinux labeling (and support labeling disabled).
I plan to drop the old path and hardcoded tar fixtures once this lands.
> tests: Add much beefed up alternative path for test framework

- lib/src/tar/export.rs
- lib/tests/it/main.rs
This adds two missing standard repo subdirectories, `state` and `extensions`. The former is required for proper `fsck` usage.
It also fixes an unrelated test which is currently not building, due to a merge overlap.
> tar/export: add 'state' and 'extensions' repo subdirs

- lib/Cargo.toml
Changes:
* tar/export: add 'state' and 'extensions' repo subdirs
* tests: Add much beefed up alternative path for test framework
* lib/src/tar/write: make sure we add the links when filtering the tar
* tests: two more small test suite patches
* tar: Add a debug function to filter tar
* cli: Use structopt's `TryFrom` support for parsing `ostree::Repo`
* tests: A few more test suite patches
* testsuite: Port to `sh-inline` 0.2
* tar/import: Don't crash on extant object
* tests: Factor out test fixture as a separate module
* tar/export: use full path as link target
* tar/export: export empty xattrs in v1 format
* cli: Drop use of `select`
* tar/v1: introduce object types for split xattrs
* container: Hard depend on `skopeo copy --digestfile`
* container/encapsulate: Support copying commit …
> ostree-ext: release 0.6.4

- lib/src/tar/export.rs
- lib/tests/it/main.rs
The containers/storage stack fails if it sees duplicate files.
Fix the bug introduced in the format version rework that passed
the object checksum instead of the xattrs checksum into the "seen"
map.
While we have the patient open, I noticed that we can optimize
things a bit and pass ownership of the checksum into the map.
> tar/export: Fix duplicate xattrs in tar stream

- lib/src/container/encapsulate.rs
- lib/src/refescape.rs
- lib/src/tar/import.rs
Fix a few clippy lints from new Rust 1.59 version
---
> Fix a few clippy lints from new Rust 1.59 version

- lib/src/bootabletree.rs
- lib/src/lib.rs
- lib/tests/it/main.rs
Right now this only offers an API to find the kernel directory,
but I could imagine we do more stuff here in the future.
I think this will be generally useful (e.g. ostree and rpm-ostree have
duplicate code for this) as is, but it's specifically prep for using
this in container layer splitting.
> bootabletree: New module with helpers for bootable ostree commits

- lib/src/tar/import.rs
Move the check for object type earlier, so we provide
a clearer error message.  Hit this when trying to
pull an unsigned commit in the tests.
> tar/import: Improve error for unsigned commit

- lib/src/fixture.rs
- lib/tests/it/main.rs
Add GPG signature on the commit object to match the current bits.
> tests: Port two tests to v1 fixture

- lib/src/container/encapsulate.rs
- lib/src/tar/write.rs
I decided to suppress the ref-vs-not ref one for now, hopefully
clippy gets fixed.
> Fix clippy lints with `cargo 1.60.0-beta.1 (ea2a21c 2022-02-15)`

- lib/src/fixture.rs
- lib/tests/it/main.rs
tests: Port two more tests to v1 fixture
Ongoing work to use the updated fixture.
---
tests: Port another two tests to v1 fixture
Ongoing work to use the updated fixture.
---
> tests: Two more fixture porting patches

- lib/src/fixture.rs
- lib/tests/it/main.rs
Will remove the old one in a followup.
> tests: Port all remaining tests to v1 fixture

- lib/src/cli.rs
- lib/tests/it/main.rs
I want to use them in rpm-ostree too.
> cli: Make parse functions public

- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/container/store.rs
Extend our image state struct to include the manifest and image
configuration (if available, only in v1).
Add a `container image history` CLI verb which prints it.
> container: Add manifest/config to image query, add `image history` CLI

- lib/src/cli.rs
- lib/src/container/deploy.rs
Right now in coreos-assembler we have code that wants to know
the exact deploy root, and for that with layered images we need
the merge commit ID.
First, change the deploy API to return the image state.  There's
no reason to just throw it away.
Add an option to the CLI which writes the commitid to a file.
> container: Add `--write-commitid-to` for `image deploy`

- lib/Cargo.toml
The biggest thing here was the merge of "chunked ostree" support in
https://github.com/ostreedev/ostree-rs-ext/pull/123
cascading into various API changes.
But I think it's working, let's cut 0.7 so the next rpm-ostree can
roll in the support.
> Bump to 0.7.0 (lots of semver-incompat API changes)

- lib/src/container/store.rs
Yeah...another big bug that snuck through in the last release.
We can't hard require the new format label, it breaks
compatibility with old format layered images.
> Fix pulling format 0 layered images

- lib/src/cli.rs
- lib/src/ima.rs
ima: Clarify that key is a path
No functional changes, it's just clearer.
---
ima: Only do IMA signatures, not EVM
Now, there is high alignment between ostree and EVM around ensuring
that the security xattrs are immutable/signed too; but
as I understand things, this attribute is really intended to be
machine-local.
---
ima: Don't overwrite existing signatures by default
A use case here is where rpm-ostree may propagate existing IMA
signatures from RPMs, but one wants to add signatures for other
files that aren't signed (for example, the RPM database and non-packaged
files).
---
ima: Use an ostree transaction
It's cleaner and more efficient.
---
> ima: various fixes

- lib/src/cli.rs
- lib/src/container/store.rs
Part of https://github.com/ostreedev/ostree-rs-ext/issues/277
When we only supported one big ostree tarball, our current
single u64 progress notification was OK.  But clients (including our
CLI) really want more dynamic progress notifications.
This adds support for an optional channel that receives started/finished
notifications for layers.  Note that the client *must* read from
this channel if they request it. The channel is not lossy.
> container: Add support for layer fetch notifications

- ci/priv-integration.sh
- lib/src/cli.rs
- lib/src/container/store.rs
- lib/tests/it/main.rs
This is a kind of important thing for production usage.  Implementation
was pretty straightforward.
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/146
> store: Implement container image removal and layer garbage collection

- lib/Cargo.toml
We only use the `cmdext` bits right now, not the atomic writes.
Widen our compatibility matrix so we can be built with both.
> build: Be compatible with cap-std-ext 0.25

- .github/workflows/rust.yml
- deny.toml
See https://crates.io/crates/cargo-deny
This looks like a really nice tool, let's use it to validate
license compatibility mainly.   But I also added `sources` and
`bans`.
> ci: make use of `cargo-deny` for baseline license check and crate dups

- .github/workflows/rust.yml
- ci/ima.sh
- lib/src/cli.rs
- lib/src/ima.rs
- lib/src/integrationtest.rs
I went to add testing for our IMA bits and I tripped over a bug; we
are going out of our way to store a trailing `NUL` character in
the ostree xattrs for the key name.  We should not do this, because
it will break fsck.  What we end up passing to the kernel looks like
`security.ima\0\0`, and the kernel being C will happily take that
to mean `security.ima`.  But the checksum we computed originally is
using `security.ima\0`, not what we will read back from disk as
`security.ima`.
> Fix extra NUL char in IMA xattr, add tests

- lib/src/tar/import.rs
I'm writing some code around changing commit metadata, and
it took me an embarassingly long amount of time to figure out
that it wasn't my code that was broken - it was this error message.
In this case, output the actual next object type we found instead
of saying "commit" which we already did find.
> import: Fix error message for missing commit metadata

- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/container/store.rs
- lib/src/container/unencapsulate.rs
- lib/tests/it/main.rs
container: Remove current byte-level progress option
We need to rework this to have useful per-layer information.
---
container: Add new byte-level progress
This new byte-level progress API allows clients to render
fine-grained download progress of individual layers.
Notably, it replaces the previous broken API which operated
on the *decompressed* stream - but we don't know the total
size of that.  This one operates on the compressed stream,
and we have the total in the manifest so we can render
an accurate progress bar.
---
cli: Use byte progress for containers
We can now show an accurate download progress.
---
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/277
> container: Precise byte-level progress reporting

- lib/src/container/encapsulate.rs
I happened to be looking at this code and realized we didn't
need to do either `unwrap()` here.
> container/encapsulate: Drop two `unwrap()`

- lib/src/chunking.rs
- lib/src/container/encapsulate.rs
- lib/src/tar/export.rs
container/tar: Thread commit checksum down into tar writer
Prep for future refactoring where we will want to cache things
related to it.  We don't have any design for emitting multiple
commits into a single tar stream, so drop that implicit ability.
---
container/tar: Pass ownership of chunks down into export
There's no reason to keep all the data alive until the export is
done, and it may allow us to optimize things in the future.
---
tar/export: Make constructor fallible
Prep for a future patch which will add actually fallible code there.
---
tar/export: Load and cache commit object
The writer can only write a single commit.  Having this data
already loaded will help with future patches for the chunked
export.
---
> container/tar: Prep patches for export fixes

- lib/Cargo.toml
We use `Sender::send_replace` which was added in 1.13.0:
https://github.com/tokio-rs/tokio/pull/3962
Closes: #316
> lib: Bump tokio minimal version to 1.13.0

- lib/src/cli.rs
- lib/src/integrationtest.rs
In various places we're lazy about properly using async; e.g.
some of the test fixtures do a ton of blocking I/O.  None of that
really matters honestly as long as the *core* library does
things properly.
This bit of code in the test case was very hackily re-entering
the async context that we already have from `main`; but it only
works on the multithreaded tokio and we're aiming to switch to
single threaded.
That was just lazy of me; it was actually not at all hard to just
properly add a few `async fn` and `await`.
> integrationtest: Properly thread `async` through to test helper

- lib/src/container/mod.rs
- lib/src/container/ocidir.rs
- lib/src/lib.rs
I want to do some more unit-test-style validation of our exported
container images.  Now, we could have the tests directly
use the [imageproxy][imageproxy] but it's very async-oriented
which is heavy for the tests.
[imageproxy]: https://github.com/containers/containers-image-proxy-rs
> tests: Expose `ocidir`, but only when testing

- lib/src/container/encapsulate.rs
I'd noticed that some of our images were large but hadn't looked
closely.  I now really wish I had...
I think this regressed quite a while ago during a refactoring.
> container: Enable compression by default

- lib/src/container/encapsulate.rs
container: Do continue to skip compression for `containers-storage:`
Fixes previous commit.
---
container/encapsulate: Fix `skip_compression` docstring
Remove an accidental double negative.
---
> Compress fixes

- lib/Cargo.toml
- lib/src/fixture.rs
- lib/src/ima.rs
- lib/src/tar/export.rs
Our semver train is fun; updating cap-std for us involves a semver
bump for ostree because it exports public types from that.
We also have our utility crate `cap-std-ext` in the mix that needs
bumping.  And we have `sh-inline` which depends on all this.
I had to bump semver for all those at once.  I'm now regretting
`sh-inline`'s existence, or at least its dependency on cap-std.
---
> Port to cap-std 0.25, ostree 0.15, sh-inline 0.3

- cli/Cargo.toml
- cli/src/main.rs
- lib/Cargo.toml
I saw https://www.reddit.com/r/rust/comments/v8e9fa/local_async_executors_and_why_they_should_be_the/
go by and I think it's a good argument why one should use single-threaded
tokio by default.
There's more to do around potentially using
https://docs.rs/tokio/latest/tokio/task/struct.LocalSet.html
etc.
> Use single-threaded tokio by default

- lib/src/chunking.rs
- lib/src/tar/export.rs
- lib/tests/it/main.rs
Depends:
- https://github.com/ostreedev/ostree-rs-ext/pull/327
- https://github.com/ostreedev/ostree-rs-ext/pull/326
---
tests: Validate structure of chunked image ostree layer
Chunked images are format v1 tar; let's add some unit-test style
code that validates the tar structure there in the same way we
verify direct tar exports.
Prep for fixing https://github.com/ostreedev/ostree-rs-ext/issues/309
---
chunking: Include all directories in ostree layer
This is prep for fixing https://github.com/ostreedev/ostree-rs-ext/issues/309
but it will not fix it on its own; to do that we need to introduce
a new chunked format.  That is forthcoming.
In the default tar export, we walk a commit from the "root".  When
exporting chunked images (what will soon be called "chunkedv0")
we instead export …
> chunked: Include all directories

- ci/priv-integration.sh
- lib/src/container/encapsulate.rs
- lib/src/container/mod.rs
- lib/src/container/store.rs
- lib/src/container/update_detachedmeta.rs
- lib/src/fixture.rs
- lib/src/integrationtest.rs
- lib/src/tar/export.rs
- lib/tests/it/main.rs
Depends: https://github.com/ostreedev/ostree-rs-ext/pull/328
---
container: Introduce an `ExportLayout::ChunkedV1`
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/309
I discovered that (what are now called) "chunkedv0" images were missing some
directories like `/tmp`.  This is because the way chunking was implemented
was...basically broken.
In chunking v0 we have:
- content objects
- content objects
- ...
- ostree layer (commit, ostree metadata)
- Any derived layers
But...we really want to "mirror" in the tar stream in a proper
fashion everything that's in the ostree layer. Particularly, in order
to ensure e.g. correct permissions/ownership, the directory entries
must come first.
And logically, it makes sense to have the layer bearing the ostree
commit and the ostree metadata …
> container: Introduce an `ExportLayout::ChunkedV1`

- lib/src/container/mod.rs
When compiling from an external crate, dead code analysis hits
a few things that we don't currently use.
> lib/container: `#[allow(dead_code)]` for ocidir

- .github/workflows/rust.yml
- cli/Cargo.toml
- lib/Cargo.toml
Our project is a workspace, and `cargo build` will build both `cli/`
and `lib/`.  Feature unification means the build gets all tokio
features.
But, I want trying to use the rust-analyzer ability to run an
individual test, and that broke with the recent tokio feature
cleanup because we're trying to just build the library, which
actually does need `io-std`.
(For us, all the code for the CLI is in the library)
So move the feature there, and add CI covers individual builds.
> Move `io-std` tokio feature into `lib`

- lib/src/container/store.rs
I happened to be looking at this code and noticed we can
lazily create the error, which is nicer.
> container: Lazily create error

- deny.toml
See https://github.com/dtolnay/unicode-ident/pull/9
This is a FOSS license, see e.g.
https://fedoraproject.org/wiki/Licensing/Unicode
> deny: Allowlist `Unicode-DFS-2016`

- lib/src/fixture.rs
- lib/tests/it/main.rs
tests: Emit expected modes in octal
Easier to read this way.
---
tests: Add two subdirectories with identical content
Prep for fixing https://github.com/coreos/fedora-coreos-tracker/issues/1258
---
tests: Pass tar entries by reference
Prep for testing the full tar export vs chunked container paths
better.
---
tests: More refactoring of expected tar handling
Add a missing 'return Ok(())` so we can split the tar stream validation
to do:
- validate prelude
- validate contents
We were also missing validation for content objects before, so fix
that!
The chunked container path in particular will need to handle content
validation differently from the "all in one" tarball.
---
tests: Verify at least one pkgdb entry is there
Prep for fixing https://github.com/ostreedev/ostree-rs-ext/issues/339
---
> tests: Prep for fixing identical subdirectory export

- lib/src/chunking.rs
- lib/src/fixture.rs
- lib/tests/it/main.rs
See https://github.com/coreos/fedora-coreos-tracker/issues/1258
Regression from https://github.com/ostreedev/ostree-rs-ext/pull/331
Currently rpm-ostree emits two identical subdirectories in
`/usr/lib/sysimage/rpm-ostree-base-db` and `/usr/share/rpm`, and the
chunking export skips emitting this incorrectly.
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/339
> chunking: Recurse on duplicate directory trees

- lib/src/tar/export.rs
- lib/tests/it/main.rs
Depends https://github.com/ostreedev/ostree-rs-ext/pull/338
---
container: Use tar format v1 for container chunks too
Amazingly while I was working on a different bug
I stumbled across the fact that the chunked path was using format v0
tar streams.
Fix that.
>  container: Use tar format v1 for container chunks too

- lib/src/cli.rs
I hit this when doing
`ostree-ext-cli container unencapsulate --repo=tmp/repo ostree-remote-registry:fedora:quay.io/coreos-assembler/fcos:testing-devel`
without a configured `fedora` remote.
> cli: Don't panic on errors from unencapsulation

- lib/src/lib.rs
xref https://github.com/rust-lang/rust-clippy/issues/9260
> lib: Extend clippy lints to deny `dbg!` and `todo!`

- lib/src/cli.rs
- lib/src/container/encapsulate.rs
container: Make `skip_compression` really use gzip fast, not none
Not doing any compression at all is quite bad for tar streams
which have a ton of duplicate data.
---
cli: Add `container encapsulate --compression-fast`
For the use case of exporting to a temporary OCI directory, which
we in turn then want to push into `containers-storage:` which
is going to decompress it again.
This will be used for e.g.
https://github.com/coreos/rpm-ostree/issues/3900
---
> cli: Add `container encapsulate --compression-fast`

- lib/src/tar/export.rs
- lib/src/tar/import.rs
- lib/tests/it/main.rs
Although the OSTree commit checksum is in a label on the container
image, sometimes we need to be able to inspect the commit from within
the container itself.
Rather than forcing tools to look through the whole repo for a commit
object, write a canonical `base` ref pointing to it.
Related: https://github.com/ostreedev/ostree/pull/2691
> container: write `base` ref

- lib/src/container/unencapsulate.rs
- lib/tests/it/main.rs
I plan to use this as part of implementing `rpm-ostree compose container`
for change detection.  Basically we want to get the inputhash from
the metadata/labels.
> container: Add an API to fetch both manifest and config

- lib/Cargo.toml
This just includes a change to generate an `ostree/encapsulated`
ref in containers, and a new API to fetch both manifest and config.
---
> Release 0.8.3

- lib/src/tar/export.rs
- lib/tests/it/main.rs
This partially reverts 30dee81c22ad5cb90e77198d3ddbcc25d388afb5
We *do* keep the code which ignores the presence of the file during
import, as an aid to future compatibility.
We can't do this by default for quite a while until support
for reading/ignoring the file has been out in the wild for e.g.
at least a month or two.
> Revert writing `ostree/encapsulated` ref

- lib/src/chunking.rs
- lib/src/refescape.rs
- lib/tests/it/main.rs
I discovered `cargo clippy --fix` exists...I'd been doing it BY HAND.
:facepalm:
This reaches into the test code too.
> Fix misc clippy lints

- lib/src/container/store.rs
- lib/src/fixture.rs
- lib/tests/it/main.rs
tests: Propagate metadata from prior commit
We want in particular things like `ostree.bootable`.
---
tests: Use `#[track_caller]`
This way panics are properly attributed to the real source.
---
tests/fixture: Inject `ostree.bootable` by default
Since that's our intended use case for now.
---
container: Hard require `ostree.bootable` key
We want to give a clear and useful error when someone tries
to pull a non-ostree-based container image.
---
>  container: Hard require `ostree.bootable` key

- lib/src/container/store.rs
- lib/src/lib.rs
- lib/src/ostree_manual.rs
- lib/tests/it/main.rs
A long time ago, in a galaxy far far away, a few of us in the
ostree space did some initial work on Docker-related things; specifically
support for whiteouts landed in
https://github.com/ostreedev/ostree/commit/baaf7450da8a3870e8a42f0cdd4e0ea0ed5018d6
I wish at that time we'd realized how we could more natively
support fetching containers; but, it never occurred to me to fork
off skopeo to do all the heavy lifting for the *fetch* side, which
would have been a lot of work to reimplement particularly in C.
Oh well, better late than never!
Anyways, that whiteout processing was only designed to happen at
checkout time - i.e. when materializing the final filesystem tree.  I
think this was actually a misdesign and we should add
`ostree_mutable_tree_write_with_whiteouts` so that the whiteouts …
> container/store: Process whiteouts

- lib/Cargo.toml
This adds a notable new feature in correctly handling Docker/OCI
whiteouts (file deletions) as well as accepting (but not writing)
refs in the tar stream.
> lib: Release 0.8.4

- ci/priv-integration.sh
chunked v1 has had time to make it to FCOS; manually copy the
*old* images now to my quay.
> ci/priv-integration: Update image fixtures

- lib/src/commit.rs
I ended up rewriting a lot of this so we could more properly unit test it.  But the problem here boils down to `move ||` having *moved* the error counter into the closure, but since it's copy it made a new copy.
> container/commit: Actually return an error code

- lib/src/bootabletree.rs
- lib/tests/it/main.rs
See https://github.com/coreos/rpm-ostree/pull/3966#discussion_r955281628
I want to switch over rpm-ostree to use this API instead of
reimplementing it.
This also adds test coverage for the existing GFile based API.
> bootabletree: Add an API to find kernel in fs checkout too

- lib/src/cli.rs
- lib/src/container/deploy.rs
- lib/src/container/store.rs
In https://github.com/coreos/coreos-assembler/pull/2523 we
taught coreos-assembler how to generate disk images with a
"pre-pulled" container image.  This means that the *first* OS update
will use shared layers.
However...right now running e.g. `rpm-ostree rebase quay.io/newimage`
won't necessarily prune the previous image.  (This may be considered
a bug)
But in practice, particularly for RHEL CoreOS we may not want to have
a default image reference - we don't (necessarily) want typing
`rpm-ostree upgrade` to do something.
With this, we can effectively pre-pull just the layers but not
the final image.
> deploy: Add a `--no-imgref` option

- lib/src/cli.rs
- lib/src/container/store.rs
- lib/tests/it/main.rs
And use it consistently in both pull and deploy paths.
I also plan to make this very visible in rpm-ostree.
Motivated by a private chat discussion with someone not realizing that files put in `/var` in a container build would just be discarded.
> container: Add an API to warn about non-ostree compatible content

- lib/Cargo.toml
Mainly to get the deploy changes out so we can get a firstboot path in OCP that doesn't involve double reboot.
> Release 0.8.6

- lib/src/container/encapsulate.rs
- lib/src/container/ocidir.rs
- lib/src/container/update_detachedmeta.rs
- lib/src/integrationtest.rs
- lib/tests/it/main.rs
I want to teach coreos-assembler to maintain an oci directory with version tags for builds instead of using an ostree repository.
It now works to do e.g.:
```
$ ostree-ext-cli container encapsulate --repo=tmp/repo 36.20220920.dev.0 oci:tmp/builds:36.20220920.dev.0
$ ostree-ext-cli container encapsulate --repo=tmp/repo 36.20220920.dev.1 oci:tmp/builds:36.20220920.dev.1
```
But in an OCI/container native build flow, we'd write the OCI builds not as `.ociarchive` but in an oci directory `builds-oci` or so.
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/154
> container: Support writing tags to `oci:` directories

- ci/container-build-integration.sh
- lib/src/commit.rs
ci: Also check via podman
It turns out that podman adds default mounts in `/run` which
means there's a behavior difference here.
But we want to cross check with both on general principle.  I was
just using `docker` because I thought podman might not be installed
on the stock GH action runner, but it apparently is.
---
commit: Ignore files and directories not on the root mount
podman injects e.g. `/run/.containerenv` as a tmpfs mount.  We should
not attempt to remove this - it will be gone when podman goes to
write the tar stream itself.
Also in the general case, traversing and recursively removing
is potentially really dangerous if e.g. someone mounted an external
drive during a container build process at say `/var/srv`.  Hopefully
most of those cases would be read-only, but still. …
>  commit: Ignore files and directories not on the root mount

- lib/Cargo.toml
We need to get the `ostree container commit` fix out.
> Release 0.8.7

- cli/Cargo.toml
- lib/Cargo.toml
- lib/src/cli.rs
- lib/tests/it/main.rs
This reworks CLI handling logic, porting to latest clap v3.
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/373
> lib: port CLI handling to clap v3

- ci/container-build-integration.sh
- lib/src/cli.rs
- lib/src/container_utils.rs
- lib/src/integrationtest.rs
Apparently, `docker buildx build` creates containers without `/.dockerenv`.  I debated forcing on a `container=oci` environment variable for our containers, but upon some reflection I think it's about equally as clean to loosen our container detection logic.
The presence of a bare-split-xattrs ostree repo is a powerful signal. Let's use that as the signal, unless overridden by strong contrary evidence:
- We're running under systemd
- We are apparently on a booted ostree systemd
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/380
> container: Loosen container detection to work with `docker buildx`

- lib/src/cli.rs
- lib/src/container/store.rs
lib/container: Add context to prepare/import
I was debugging an error and was trying to figure out which
of these it was coming from (the answer was neither though).
---
cli: Fix error when using deploy --target-imgref
I was trying to use https://github.com/coreos/coreos-assembler/pull/2523
to test something and discovered that
https://github.com/coreos/coreos-assembler/pull/2523
regressed this.  We need to use the target imgref if provided.
---
> Fix deploy error

- .github/workflows/rust.yml
- ci/priv-integration.sh
- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/container/store.rs
- lib/src/lib.rs
- lib/src/logging.rs
I was logged into one of my OpenShift machines live and watching `journalctl -b -u rpm-ostreed -f` during an upgrade, and was surprised not to see any useful output.
This is because of course rpm-ostreed logs everything to the client, in this case the MCD.
I think we should also duplicate these messages directly in the journal.  libostree does something similar when fetching via HTTP.
> Automatically log some container metadata to systemd journal (if avail)

- lib/src/container/mod.rs
We've seen a weird error out of the container stack when we're not authorized to fetch an image, *and* no pull secret is set up.
e.g.  https://github.com/coreos/rpm-ostree/issues/4107
```
error: remote error: getting username and password: 1 error occurred:
* reading JSON file "/run/containers/62011/auth.json": open /run/containers/62011/auth.json: permission denied
```
We don't want the containers/image stack trying to read the "standard" config paths at the moment for a few reasons; one is that the standard paths conflate "root" and "the system".  We want to support separate pull secrets.  But, it should also work to symlink the authfile.
> container: Force on anonymous fetches if no config file

- lib/src/cli.rs
Previously I added it to the API, intending to use it for FCOS, but hadn't actually tested that at the time.
I'm still not entirely sure we will, but let's add it to the CLI anyways.
> cli: Add `--no-imgref` to deploy option

- .github/workflows/rust.yml
- lib/src/logging.rs
I noticed an error message when we're doing the deployment in supermin in coreos-assembler.
> logging: Don't write to journal if not running systemd

- .github/workflows/rust.yml
- ci/priv-integration.sh
- lib/Cargo.toml
- lib/src/container/encapsulate.rs
- lib/src/container/store.rs
- lib/src/fixture.rs
- lib/src/tar/export.rs
- lib/tests/it/main.rs
Add a `compat` feature
This is the first step towards disabling our support for old
tar formats and the legacy container formats.
When the `compat` feature is off, everything defaults to v1
format, and we reject parsing the old v0 container images in
particular.
---
Bump semver to 0.9
Because we have an off-by-default `compat` feature.
---
> Add compat feature and bump semver to 0.9

- cli/Cargo.toml
- lib/src/lib.rs
cli: Don't publish
We aren't productizing this CLI entrypoint.
---
Don't expose `ostree_manual` API at all in non-test mode
This avoids dead code warnings for external crate users.
---
> Two minor patches

- .github/workflows/rust.yml
- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/docgen.rs
- lib/src/lib.rs
It's about time we had online (and shipped in packages) docs for our tools.
Some code inspired/taken from https://github.com/coreos/coreos-installer/blob/main/src/cmdline/doc.rs
> Initial support for generating manpages

- lib/src/fixture.rs
- lib/src/tar/export.rs
- lib/tests/it/main.rs
This is an echo of https://github.com/ostreedev/ostree/pull/2198/commits/558720e7aa1870cbbdb4a0dc22a3968d116daec3
If we hardlink zero sized files, then any modification to them will result in possibly *many* hardlinks needing to be reproduced when serializing to tar, which is definitely suboptimal.
But further, it provokes a bug in our import path; when processing derived layers, we need to handle *both* cases of having the file in `/sysroot` be the source as well as the destination of the hardlink in the tar stream.
> tar/export: Don't create hardlinks to zero sized files

- ci/priv-integration.sh
- lib/src/cli.rs
- lib/src/container/store.rs
Prep for handling image pruning better.  The way things are kind of expected to work today is that for a deployed ostree commit, we have *two* refs which point to it - one like e.g. `fedora:fedora/x86_64/coreos/stable`, as well as the "deployment ref" like "ostree/0/1/1" which is a synthetic ref generated by the sysroot core.
We want to be able to remove the container image refs - but doing so today subjects the *layer* branches to garbage collection.
Fix this by looking at the deployment refs as well as the set of images when computing the set of references for container images.
> container: Add deployed commits into set of GC roots

- lib/src/integrationtest.rs
- lib/src/tar/import.rs
- lib/src/tar/write.rs
- lib/tests/it/main.rs
Builds on https://github.com/ostreedev/ostree-rs-ext/pull/406
---
tar/import: Handle hardlinked changes into /sysroot
Some container build processes run without overlayfs inode indexing
on - in this common scenario, overlayfs is not quite POSIX compliant
because it will break the hardlink instead of modifying all versions.
We need to handle this case of having *all* names for a hardlinked
file being modified though too.  If the serialized tar stream
has the file in `/sysroot` be the canonical version, then because
we drop out that file here, we'll fail to import.
Fix this by significantly beefing up the tar filtering/reprocessing
logic:
- When we see a *modified* file in `/sysroot` with a nonzero timestamp,
cache its data into a lookaside temporary directory
- If we then see a hardlink to …
> tar/import: Handle hardlinked changes into /sysroot

- lib/Cargo.toml
This has two major fixes:
- Better support for image pruning
- Handling of hardlinked files into `/sysroot` which can occur with some container build systems
> Release 0.9.1

- lib/src/container/mod.rs
It's preferred to implement `FromStr` where possible in addition to `TryFrom` because it's usable in more contexts.  Specifically in this case, with `clap` and `value_parser`.
> container: Implement FromStr for OstreeContainerReference

- lib/src/cli.rs
- lib/src/container/encapsulate.rs
- lib/tests/it/main.rs
This is to aid https://github.com/coreos/coreos-assembler/pull/3214 which is trying to inject the metadata key `fedora-coreos.stream` into the container image.  However, this value will only be present in Fedora derivatives, and not RHEL/CentOS.
Add support for copying a key only if present, instead of erroring if it's missing.
> container: Add support for copying optionally-present keys

- lib/src/lib.rs
- lib/src/sysroot.rs
A common use case is wanting to acquire a locked system root.  Add a helper function which handles this and returns a guard object that can be dereferenced to a sysroot.
> Add a `sysroot` module with helper for `SysrootLock`

- .github/workflows/rust.yml
> Node.js 12 actions are deprecated. For more information see:
> https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> ci: Switch to checkout@v3

- .github/workflows/rust.yml
- cli/Cargo.toml
- lib/Cargo.toml
Prep for bumping ostree, which also bumps MSRV.
xref https://github.com/containers/containers-image-proxy-rs/pull/40/commits/12cdbf5af5ef40b312df14d7968e30bfbbb02067
- Use `checkout@v3` to avoid deprecation warnings
- switch to https://github.com/dtolnay/rust-toolchain after seeing https://www.reddit.com/r/rust/comments/z1mlls/actionsrs_github_actions_need_more_maintainers_or/
- bump to rust-cache@v2
> Update MSRV, revamp CI

- lib/tests/it/main.rs
With a new enough rpm-ostree, this test will always fail if we're built in compat mode.  I'm hitting this locally, but it looks like the latest rpm-ostree only made it to testing-devel 2 days ago.
> tests: Always use v1 for compat testing

- lib/src/tar/export.rs
- lib/tests/it/main.rs
This is a bit of a hack, but basically the ostree model of empty `/var` defers creation of basic directory structure to e.g. `systemd-tmpfiles`, but that isn't run in containers.
For now, let's keep this as the only special case.  Perhaps down the line we may actually need to effectively parse/execute systemd-tmpfiles inside the stream in the future, but hopefully we can avoid that.
Many things are going to use `/var/tmp` during image builds, but that's much less likely with e.g. `/var/log`.
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/417
> tar/export: Always generate `/var/tmp`

- lib/src/container/mod.rs
- lib/src/integrationtest.rs
- lib/src/isolation.rs
- lib/src/lib.rs
This effectively lowers into this project code from https://github.com/coreos/rpm-ostree/pull/3937/commits/d661e8f974f8d2550a865c2866476160e333ec72
We want to do this by default; we use the `nobody` user here.
> Add an isolation module, use it for pulls by default

- ci/priv-integration.sh
- lib/src/container/store.rs
The formatting was confusing before because one could associate the number both before and after "layers".
> store: Tweak status message for layers

- lib/src/container/mod.rs
- lib/src/sysroot.rs
sysroot: Make underlying value `pub`
Since we expose it via `Deref` anyways.  Prep for usage in bootc.
---
impl Display for SignatureSource
This is the cleaner way to do things, and I want this in bootc.
---
> Two minor bits

- lib/src/container/store.rs
To aid future debugging.  We should probably add some of this into the systemd journal always too, but that can be done in the future.
> store: Add some `tracing::` to GC paths

- lib/src/cli.rs
- lib/src/container/deploy.rs
For reuse in bootc.  (Until it becomes a daemon, then this all needs to be redone again)
> cli: Make more output/progress functions `pub`

- lib/Cargo.toml
- lib/src/container/ocidir.rs
This is maintained as part of https://github.com/awslabs/tough and is used by several crates, including the pure Rust OCI crate https://lib.rs/crates/oci-distribution
The immediate motivation is dropping our duplicate `itoa` dep.
> lib: Switch to olpc-cjson

- lib/src/isolation.rs
See https://github.com/coreos/rpm-ostree/issues/4237 for the original report.
Only in locales that use the dotless I case conversion we hit on the fact that util-linux uses `strcasecmp` which is locale-sensitive (It shouldn't be for this, because we're not accepting translated
signal names.  It should be using an ASCII-only string comparison)
Anyways, we can work around this by omitting the leading `SIG` ourselves.
> isolation: Avoid bug with `--pdeathsig SIGTERM` in Turkish locales

- ci/priv-integration.sh
- lib/src/cli.rs
- lib/src/container/store.rs
- lib/tests/it/main.rs
Depends https://github.com/ostreedev/ostree-rs-ext/pull/443
This backports the GC work to the (new) 0.8 branch.  Thankfully it was all clean cherry :cherries: picks!
--- 
Remove test parsing old export
The newer rpm-ostree we ship now no longer supports it.  We
aren't going to change anything in the export path on this
branch, so we don't need it.
---
tests: Update to non-deprecated chrono API
The deprecation was introduced in a new chrono release and
is triggering our clippy lints.
(cherry picked from commit 7875bb33ab37807c1cf3f0ca96297d28c1ea0feb)
---
ci: Retarget for this branch
---
container: Prune image layers by default
A while ago we added APIs to do this, but we should really
do it by default when fetching upgraded images.  Otherwise
we effectively leak space.
(cherry picked from …
> [0.8] backport gc

- lib/src/container/store.rs
- lib/src/tar/import.rs
tar: Add error prefixing around commit verification
In an error message we got a bare
`error: No such remote ...`
Let's clarify where this is coming from.
---
store: Add error prefixing on base import
On general principle; we got a "bare errors" in the case of
a missing ostree remote.
---
> two error prefixing patches

- lib/src/container/store.rs
- lib/src/tar/import.rs
I looked through more of the container and tar paths, and decided to add even more error prefixing to aid future debugging.
> Add even more error prefixing

- lib/src/container/mod.rs
- lib/src/container/store.rs
- lib/tests/it/main.rs
This makes it more convenient for higher level tools to display the associated image version number.
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/450
> container: Add an API to retrieve the version number

- lib/src/fixture.rs
- lib/src/integrationtest.rs
- lib/tests/it/main.rs
We're not supporting this anymore; continue to trim it from our tests.
(There's even more to do here, but this compiles)
> tests: Trim some v0 export format code

- lib/src/container/encapsulate.rs
- lib/tests/it/main.rs
And add an API to allow opting-out of the legacy label.
> container: Add standard OCI version key by default

- lib/Cargo.toml
Two new APIs, and we now also inject the standard OCI version annotation.
> Release 0.10.6

- ci/priv-integration.sh
- lib/src/cli.rs
This clones the nicer bootc syntax which does away with forcing users to understand the image reference strings.
> deploy: Add optional `--image` syntax

- lib/src/container/store.rs
This will allow us to not hardcode rpm-ostree in the future, and will be more extensible in general.  This is targeted for use in bootc.
> container/store: Add a well-known ref for holding base images

- lib/Cargo.toml
Colin Walters (5):
ci: We can now pull from containers-storage
deploy: Make `--stateroot` default to `default`
deploy: Add optional `--image` syntax
container/store: Add a well-known ref for holding base images
Release 0.10.7
> Release 0.10.7

- .github/workflows/rust.yml
- cli/Cargo.toml
- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/container/deploy.rs
- lib/src/container/mod.rs
- lib/src/diff.rs
- lib/src/fixture.rs
- lib/src/tar/import.rs
This adapts to the changes from https://github.com/ostreedev/ostree/pull/2791 in particular.
---
Bump MSRV to 1.64
Since it's what ostree requires now, due to one of its dependencies.
---
> Update to ostree 0.18

- lib/src/chunking.rs
Followup: https://github.com/ostreedev/ostree-rs-ext/pull/456#discussion_r1180747811
Fix the the repeated name of the first package in the history of oci config for each oci layer
> chunking: Deduplicate the config history for each layer

- lib/Cargo.toml
- lib/src/container/encapsulate.rs
- lib/src/container/mod.rs
- lib/src/container/ocidir.rs
- lib/src/container/update_detachedmeta.rs
- lib/src/integrationtest.rs
- lib/src/lib.rs
- lib/tests/it/main.rs
This needs to stay in sync, because it's a public API dependency of that project.  Motivated by a recent semver bump there.
> Use `oci_spec` re-exported from `containers_image_proxy`

- lib/Cargo.toml
- lib/src/commit.rs
- lib/src/container/mod.rs
- lib/src/container/store.rs
- lib/src/globals.rs
- lib/src/ima.rs
- lib/src/integrationtest.rs
- lib/src/selinux.rs
In cap-std-ext we made the mistake of making rustix a public API; the 2.0 version fixes that.
Add rustix directly here and use it.
> Bump to cap-std-ext 2.0, use rustix directly

- .github/workflows/rust.yml
- ci/priv-integration.sh
- lib/src/container/store.rs
- lib/src/lib.rs
- lib/src/utils.rs
I was doing some bootc tests and noticed that the deployment commit was different each time I ran an install.  Write the commit with the timestamp of the config (or manifest) to increase reproducibility.
> container/store: Write final commit with timestamp

- lib/src/chunking.rs
- lib/src/cli.rs
- lib/src/commit.rs
- lib/src/container/encapsulate.rs
- lib/src/container/mod.rs
- lib/src/container/ocidir.rs
- lib/src/diff.rs
- lib/src/fixture.rs
- lib/src/ima.rs
- lib/src/isolation.rs
- lib/src/objectsource.rs
- lib/src/tar/export.rs
- lib/src/tar/import.rs
- lib/src/tar/write.rs
- lib/tests/it/main.rs
tests: One run of `cargo clippy --fix`
Nothing important, just some unnecessary `&` churn.
---
lib: Ignore incorrect clippy lint about deref+`Lazy`
`cargo clippy --fix` fails to compile if we remove the `*` here.
---
tree-wide: Run `cargo clippy --fix`
Nothing important here, just the usual spam of unnecessary `&`
basically.
---
> tree-wide: Run cargo clippy --fix

- lib/tests/it/main.rs
tests: Also verify manifest digest
Just a drive by cleanup; unused variables are usually a red flag.
Let's just add an assertion here.
---
tests: Add a test for layers_with_history()
Motivated by https://github.com/ostreedev/ostree-rs-ext/issues/480
---
> Two minor test additions

- lib/src/container/encapsulate.rs
- lib/tests/it/main.rs
This is just friendlier because we want the value to be potentially useful.  It doesn't harm reproducibility because if the embedded commit timestamp is not reproducible, then the image will already not be reproducible.
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/420
> container: Set creation date to match ostree commit timestamp

- lib/src/chunking.rs
chunking: Better separate prior build from new path
Move the declarations of these variables down to the part of
code where they're used.
---
chunking: Also more cleanly separate "enough bins" path
Use `map()` for the first case to keep things more self-contained.
---
chunking: Move "prior build" bits into function
The logic here is really quite different; I think it's
clearer to have two separate functions.  This allows de-indenting
the logic for the prior build path.
---
chunking: Use a combinator to compute sum
---
> A few minor chunking cleanups

- cli/Cargo.toml
- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/docgen.rs
RFC: clap v4 comes with several additional deprecations, which I haven't yet looked at. We can either do it here, or leave it for later.
> cargo: bump to clap v4

- lib/src/container/mod.rs
This is prep for further changes where I want to compute more derived data.  There's no compelling reason to support disjoint lifetimes here; in the end we need to be OK with the shorter of the two.
> container: Make ManifestDiff have only one lifetime

- lib/Cargo.toml
(We should have bumped the semver in git before now)
But I think we're done with API changes for now, so let's go ahead and do the first 0.11 release.
> Release 0.11.0

- lib/src/container/store.rs
Fixes: https://github.com/coreos/rpm-ostree/issues/4283
> store: Pulling from container-storage needs root privileges

- lib/src/container/store.rs
Since it's intended for use by external consumers.
> container/store: Make baseimage ref prefix `pub`

- ci/priv-integration.sh
- lib/src/cli.rs
- lib/src/container/deploy.rs
- lib/src/container/mod.rs
This is part of fixing https://github.com/coreos/rpm-ostree/issues/4391 but is also in the general theme of making things less "stateful".
A huge huge mess today is `rpm-ostree rebase` and `bootc switch` both have `--retain` options which keep the previous image.
But really what we want is to use the deployments as source-of-truth; that way if e.g. an admin pins a deployment, it automatically pins the image too.
And this will help strongly align with the bootc direction in reconciling to desired state.
> deploy: Add an API to prune undeployed images

- lib/src/container/mod.rs
This will fix the need demonstrated by
https://github.com/containers/bootc/pull/106/files#diff-c163debeb7fdf9b238e5c589e0000c80684ca9a09abd408242df4bad489626a6R38
We made a historical mistake here in having our `Display` include the `:`...but it's hard to deal with because inherently the format is messy because of the `://` in `docker://`.
> container: Add an API to serialize `Transport`

- lib/src/cli.rs
- lib/src/container/store.rs
- lib/src/diff.rs
- lib/src/lib.rs
- lib/src/repair.rs
Initial code to detect the situation resulting from https://github.com/ostreedev/ostree/pull/2874/commits/de6fddc6adee09a93901243dc7074090828a1912
EDIT: Here's instructions to run this:
> podman run --rm -ti --pull=newer --privileged -v /:/rootfs --net=none quay.io/cgwalters/ostree-ext-dev provisional-repair repair --sysroot /rootfs/sysroot --dry-run
> repair: New functionality to detect (future: fix) inodes

- lib/src/cli.rs
- lib/src/container/store.rs
- lib/src/repair.rs
I plan to "productize" this repair code a bit more in OpenShift at least, and I think other admins may want to do similar outside of that too.
In order to make that more reliable:
- Better split the "fsck/--dry-run" path from "repair" i.e mutation
- Introduce a `--write-result-to` argument that outputs JSON.  This allows us to better distinguish the tristate of "OK" from "corruption detected" to "tool failed for some other reason"
Further:
- Drop the check for derived commits, let's just *always* check the inodes because it's not very expensive in the end and it's just really useful to do.
- Add checks for whether the booted deployment is potentially affected, as this is important information; we'll need to redeploy and reboot if so
> repair: Rework to be more introspectable

- lib/src/cli.rs
- lib/src/container/mod.rs
- lib/src/container/store.rs
Prerequisite for the `rpm-ostree upgrade --check` issue: https://github.com/coreos/rpm-ostree/pull/4486
Implemented:
- previous_state `LayeredImageState` object added to the `PreparedImport` object
- `export_as_string()` function is added to the `ManifestDiff` object
Note: The `previous_state` member of the struct is not actually used in the rpm-ostree issue stated above. Only the `export_as_string()` is used. However, the changes may see use in the future and can probably be left in.
See commit message for more details.
> Add previous container image state

- lib/src/container/deploy.rs
This is the same bug as
https://github.com/ostreedev/ostree-rs-ext/commit/3089166a4456cdcfa0568aedcda31eac65ac00ee but for the not-booted case.
Basically in the C API bridged to Rust we can't distinguish between "NULL array" and "zero length array".  But the _with_options path supports distinguishing them, and we want the "no kargs provided" case to not override anything.
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/502
> deploy: Don't overwrite kargs by default

- lib/src/container/deploy.rs
- lib/src/container/store.rs
- lib/src/fixture.rs
- lib/tests/it/main.rs
This fixes a regression introduced by
https://github.com/ostreedev/ostree-rs-ext/commit/9c4a75b3778a3f2fdece095f8f5f7a6289ab512dLooks
Brought up in
https://github.com/ostreedev/ostree/discussions/2978
Basically we need to make this opt-in at higher levels because encapsulating a non-bootable commit (as well as a commit that historically doesn't have that label) must be supported.
> container: Make requiring bootable field be opt-in

- lib/src/container/store.rs
Since in theory we support non-bootable cases, and we actually have a distinct label for the bootable one.
> store: Tweak error message for non-ostree containers

- lib/src/cli.rs
I was looking at `cargo bloat` and this showed up near the top twice. It's a large function and only the option parsing needs to be generic.
> lib: Dispatch to monomorphic function

- lib/src/cli.rs
To make it less likely people run into the footgun of specifying `--sysroot /sysroot` which is buggy right now
https://github.com/ostreedev/ostree/issues/2992
> cli: Make `--sysroot` optional

- Cargo.toml
- `release` should use `panic=abort` by default because we make heavy use of FFI and this is safest, and I don't think we need unwinding anyways
- The `releaselto` produces smallest binaries
> Cargo.toml: Update `release` profile, add `releaselto`

- .github/workflows/rust.yml
- cli/Cargo.toml
- lib/Cargo.toml
Bump rust-version = 1.70
clap_builder now pulls it in, and we need to follow that train...
---
ci: Drop hard errors on clippy warnings by default
It's just too much churn for too little value.
---
> Bump rust-version = 1.70 && ci: Drop hard errors on clippy warnings by default

- lib/src/cli.rs
We need to support all the proxy options so that custom authentication files can be supported, etc.
Closes: https://github.com/ostreedev/ostree/issues/3015
> cli/unencapsulate: Add proxy options

- .github/workflows/rust.yml
- Cargo.toml
- cli/Cargo.toml
There's a warning in newer Rust 1.72 about this, we do want the v2
resolver.
> Cargo.toml: Set `resolver = 2`

- lib/src/cli.rs
- lib/src/container/encapsulate.rs
- lib/src/container/skopeo.rs
- lib/src/container/update_detachedmeta.rs
Ideally we'd pass through all of the proxy options here, but doing that sanely really requires being able to do *pushes* through containers-image-proxy-rs, which is a quite nontrivial amount of work.
For now, let's pass through `--authfile` which is the main thing people want.  Anything else can be worked around by encapsulating to `oci` and then doing a `skopeo copy` from there.
cc https://github.com/ostreedev/ostree/issues/3015
> cli/encapsulate: Add `--authfile`

- lib/Cargo.toml
Because it has an important bugfix.
> lib: Require new containers-image-proxy

- .github/workflows/rust.yml
Blocking on clippy I think is just too painful for the value it provides.
> ci: Re-enable clippy, but nonblocking

- lib/src/sysroot.rs
There's a mess with `SysrootLock` because in practice, way, way too many APIs just take the plain old C `Sysroot` object.
In this project, we added a new API that requires a `SysrootLock`, which works well when everything is using ostree-ext from the start, as it is in bootc.
However in rpm-ostree we acquire the lock from C code, but want to call `remove_undeployed_images` which wants `SysrootLock`.  The only practical way out of this is to add an API which asserts that the sysroot is locked and returns this wrapper.
What would actually work better here is to drive this locking logic down into the C library.
> sysroot: Add `from_assume_locked`

- lib/src/container/unencapsulate.rs
- lib/src/tar/write.rs
container: Add a trace log for when we discard "broken pipe" error
I don't think we're hitting this in https://github.com/coreos/rpm-ostree/issues/4567
but it'd be useful to have a trace message in case.
---
tar: Hold open input stream as long as possible
I'm hoping this will help us debug https://github.com/coreos/rpm-ostree/issues/4567
```
[2023-08-30T15:00:16.554Z] Aug 30 15:00:15 qemu0 kola-runext-container-image[1957]: error: Importing: Parsing layer blob sha256:00623c39da63781bdd3fb00fedb36f8b9ec95e42cdb4d389f692457f24c67144: Failed to invoke skopeo proxy method FinishPipe: remote error: write |1: broken pipe
```
I haven't been able to reproduce it outside of CI yet, but we had
a prior ugly hack for this in
https://github.com/ostreedev/ostree-rs-ext/commit/a27dac83831297a6e83bd25c5b6 …
> tar: Hold open input stream as long as possible

- lib/Cargo.toml
- lib/src/bootabletree.rs
- lib/src/commit.rs
- lib/src/container/ocidir.rs
- lib/src/container/store.rs
- lib/src/repair.rs
- lib/src/tar/write.rs
This way things like Dependabot understand there's only one dependency to bump instead of multiple that must move in lockstep.
> Use cap_tempfile via cap_std_ext

- lib/Cargo.toml
This updates to a more modern version which will help drop out e.g. `nix-0.23` from our dependency graph - it's long obsoleted.
> lib: Bump to libsystemd 0.6

- lib/src/chunking.rs
I was hitting a panic in this section of the code; I think
triggering it involves removing packages, but I haven't narrowed
it down more precisely.
Hopefully at some point I will try to add some more unit
testing for this...
---
> chunking: Ignore ostree commit layer

- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/container/store.rs
- lib/src/fixture.rs
- lib/src/keyfileext.rs
- lib/src/repair.rs
- lib/src/tar/export.rs
- lib/tests/it/main.rs
keyfileext: Drop optional_string_list
Nothing is using this, and the underlying glib type changed
so it's annoying to keep.
---
lib: Bump to ostree 0.19, cap-std-ext 3.0
This is just "keeping up with churn":
- Newer versions of glib crates
- Bump to cap-std-ext 0.3, which bumps cap-std 2.0
---
lib: Bump to rustix 0.38
Again just keeping up.
---
lib: Bump semver to 0.12
Because we bumped ostree.
---
> lib: Bump to ostree 0.19, cap-std-ext 3.0 && lib: Bump to rustix 0.38 && Bump semver to 0.12

- lib/src/container/mod.rs
xref https://github.com/openshift/machine-config-operator/pull/3857#issuecomment-1712026017
The MCO has code which incorrectly parses these image references; because rpm-ostree defaults to writing `ostree-unverified-registry`, let's canonicalize to that because it looks better too.
> container: Canonicalize imgref to ostree-unverified-registry

- lib/src/container/deploy.rs
- lib/src/container/encapsulate.rs
- lib/src/tar/import.rs
- lib/src/tar/write.rs
- lib/tests/it/main.rs
tar: Make `WriteTarOptions` `#[non_exhaustive]`
To allow future extensibility.
---
tar: Make `TarImportOptions` `#[non_exhaustive]`
To allow future extensibility.
---
container: Make `DeployOpts` `#[non_exhaustive]`
To allow future extensibility.
---
container: Make `ExportOpts` `#[non_exhaustive]`
To allow future extensibility.
---
> A story in which `#[non_exhaustive]` is discovered

- lib/src/chunking.rs
- lib/src/cli.rs
- lib/src/container/encapsulate.rs
- lib/src/fixture.rs
- lib/tests/it/main.rs
container: Move more metadata into `ExportOpts`
This drops two extra arguments we added over time; in
a few places before we had e.g. `None, None, None` being passed
which just looks awkward.  And we also threaded through all 3
in various places.
The `ExportOpts` just needs to grow a lifetime argument, but that
turned out to not be too bad when I realized we could use the
elided lifetime `<'_>` in all methods that use it.
---
container: Make `ExportOpts` `#[non_exhaustive]`
It's intended for this purpose, where we want to be able
to add elements to the struct over time without breaking semver.
---
> container: Move more metadata into `ExportOpts`

- lib/src/cli.rs
- lib/src/container/store.rs
- lib/tests/it/main.rs
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/496
In https://github.com/coreos/rpm-ostree/pull/4486 we were working on fixing `rpm-ostree upgrade --check` with containers.
However, what we really want here is to *persist* the updated manifest (and config) that we fetch.  And if we do that, we might as well just make it part of the current `prepare()` API so it happens automatically.
In this change, we do so via detached commit metadata.  An important thing here is that the data is then automatically lifecycle bound to the merge commit - and the merge commit always changes when we fetch a new manifest.
In order to do an offline query (e.g. in rpm-ostree we want to re-synthesize a higher level summary of the queued update) add an API which allows querying a previously saved …
> container: Cache new manifest/config in prepare, add API to query

- lib/src/commit.rs
This fixes a failure I was seeing using `buildah` in Gitlab CI; it seems like `/run/secrets` ends up as a bind mount here, and because it's a bind mount it has the same device node.
With new enough Linux there's a handy attribute from the `statx` system call that will tell us whether a given path is a mount point root.  Let's use that to start.
(The other alternatives are much uglier; see the linked systemd
git source code)
We may need to end up doing some of that if we find we keep hitting this with systems that have older kernels.
> commit: Skip bind mounts too

- lib/src/cli.rs
- lib/src/container/mod.rs
This patch allows container image deployment stored in a local directory in addition to the supported remote OCI registry, OCI archive tarball, and local container storage. For example, the following command is now supported:
`sudo ostree container image deploy --imgref ostree-unverified-image:dir:/var/home/core/fcos --sysroot /var/home/core/sysroot --stateroot fedora-coreos`
The reason for making this change relates to the effort to create an FCOS qemu image from a container image input using OSBuild. OSBuild stores container image sources in a local directory in order to solve another bug and, thus, should not be changed. Therefore, to allow OSBuild to deploy from a container image, this patch is needed.
> Allows container deployment from local directory

- ci/priv-integration.sh
This change adds an integration test for deploying from a container image stored in a local directory. It is directly related a recent change to support the `dir:` transport when using `ostree container image deploy`: https://github.com/ostreedev/ostree-rs-ext/pull/544
> container: Add dir container deploy test 

- lib/src/container/deploy.rs
Looking at doing a bootc reinstall, we need the ability to retain existing deployments for this.
> deploy: Add a no_clean option

- lib/src/commit.rs
- lib/src/lib.rs
- lib/src/mountutil.rs
I copy/pasted the mountpoint check into bootc, but it'd be better to centralize.
> lib: Add mountutil module

- lib/src/container/store.rs
- lib/tests/it/main.rs
This also relates to https://github.com/containers/oci-spec-rs/pull/143
Basically getting the version from the config requires a helper, this is a lot more convenient.
> lib/container: Add APIs to retrieve version conveniently

- lib/src/container/encapsulate.rs
- lib/src/container/store.rs
- lib/src/container/unencapsulate.rs
- lib/src/tar/import.rs
- lib/src/tar/write.rs
tree-wide: Clean up usage of `tracing::instrument`
We're really verbose with `env RUST_LOG=debug`...most of
these spans shouldn't be emitting any arguments at all . And
even then let's lower to debug level for them too.
---
store: Silence extremely verbose tracing::debug
This ends up recursing into the manifest/config objects
which is a wall of spam with `env RUST_LOG=debug`.  Just print
the merge commit to start here.
---
> Quiet extremely verbose tracing::debug

- lib/src/chunking.rs
If we have a low amount of high-size packages then we will drain with an index higher than the size of the Vec which triggers a panic.
Fixes: https://github.com/coreos/rpm-ostree/issues/4646
> chunking: Handle low amount of high-size packages

- lib/src/container/deploy.rs
I don't recall now the rationale for the previous code; if we're using this path we always want to be in a container-native mode.  Currently the "unpack to pure ostree commit" gets triggered if one uses this on a container image created via raw `ostree container encapsulate`.
Anyone who wants the prior behavior should instead unencapsulate and deploy the underlying commit.
> deploy: Always use merge commit

- lib/src/tar/write.rs
- lib/tests/it/main.rs
The previous commit here (43e1648e97ef82f2cb86fd0813a5f338585eea97) handled the case of *one* hardlink, but the logic for the secondary one was backwards.
I noticed this when generating a derived image, in some cases we only end up with `/usr/lib/sysimage/rpm-ostree-base-db` as modified, which causes really confusing semantics that look like packages going missing.
> tar: Fix multiple hardlinks

- lib/src/tar/write.rs
A classic bug; we need to concurrently handle both the process exit status as well as output from its stdout/stderr streams.
I hit this hang when running `ostree-ext-cli container pull` directly and the target sysroot mount isn't writable.
> tar: Fix hang if ostree exits with failure

- lib/src/container/encapsulate.rs
In some testing, this was defeating bitwise reproducibility.
> encapsulate: Sort components

- lib/src/isolation.rs
Otherwise in some cases the containers/image stack can try to look at things like `$HOME` which might be set to `/root` if we're running outside of systemd, and that can cause permission denials.
> isolation: Also reset environment

- lib/src/container/unencapsulate.rs
In the original design of the skopeo proxy, the idea is that it shields us from the legacy Docker formats, converting everything to OCI.
That has worked - except it turns out in the case of pulling a docker-formatted image from `containers-storage`, the proxy code fails to convert the layer types.
In this case, it's easy to handle here; we only need to care about the uncompressed version in this case.
> unencapsulate: Handle legacy docker MIME type

- lib/src/cli.rs
- lib/src/container/encapsulate.rs
- lib/tests/it/main.rs
Part of https://github.com/coreos/rpm-ostree/issues/4701
Basically we should support setting arbitrary container configuration.
> encapsulate: Support setting arbitrary container config

- lib/src/tar/write.rs
- lib/tests/it/main.rs
Instead of dropping `/var` content on the floor, move it into `/usr/share/factory/var`.
With this change, a systemd-tmpfiles fragment like this: `C+ /var - - - - -`
is sufficient to get "populate /var" automatically on initial installation and across upgrades.
> Move /var content to /usr/share/factory/var

- lib/src/cli.rs
- lib/src/container/store.rs
- lib/src/lib.rs
- lib/src/ostree_prepareroot.rs
- lib/src/tar/write.rs
- lib/tests/it/main.rs
This pairs with https://github.com/ostreedev/ostree/pull/3114
Basically if ostree has an overlayfs (whether writable or a readonly composefs), we're safe to handle non-`/usr` content.
However, we still *always* drop content from the
"API filesystems" like `/run`, `/dev` etc.  Because really, no one should be adding stuff there.
> Support non-`/usr` content if ostree configured with overlayfs

- ci/priv-integration.sh
- lib/src/cli.rs
- lib/src/container/deploy.rs
Add convenient API/CLI to prune all content
This is kind of a usability regression from
https://github.com/ostreedev/ostree-rs-ext/pull/498/commits/979b93a24765ab129c6f1414388a9c7565fe3d80
"deploy: Add an API to prune undeployed images"
This new API and CLI make it convenient to prune the images,
the layers, *and* the underlying objects.
cc https://github.com/coreos/rpm-ostree/pull/4720
This API in particular is what bootc wants.  For rpm-ostree
we do still want to separate pruning refs from objects, because
rpm-ostree may have layered packages, and we only want to traverse
the ostree repo to prune objects once.
---
deploy: (style) Move external crates before internal
This is preferred style.
---
> Add convenient API/CLI to prune all content

- lib/src/container/mod.rs
- lib/src/container/store.rs
See the tracking issue https://github.com/rust-lang/rust/issues/115010
There's now a warning for this in newer Rust versions.
> lib: Fix omitted lifetime in associated consts

- lib/src/container/encapsulate.rs
- lib/tests/it/main.rs
> container: Don't include legacy `version` label by default

- lib/src/cli.rs
- lib/src/container/store.rs
- lib/tests/it/main.rs
store: Remove deprecated `copy` function
Part of semver break cleanups.
---
store: Rename `copy_as` -> `copy`
Now that the old one is removed.
---
> store: Cleanup `copy` function

- lib/src/cli.rs
- lib/src/container/store.rs
- lib/src/repair.rs
- lib/tests/it/main.rs
Knocking one thing off the semver bump TODO.
> store: Remove deprecated `query_image`, rename replacement

- lib/src/container/encapsulate.rs
- lib/src/container/store.rs
- lib/src/container/update_detachedmeta.rs
We don't support the v0 layout for a long time, this is the last remnant.
Part of semver breaking cleanups.
> Remove ExportLayout

- lib/src/cli.rs
- lib/src/container/store.rs
We should really always have it nowadays.  In the degenerate case where it somehow still isn't present, just return an empty config.
This improves ergonomics because it avoids the need to deal with the `Option` in many consumers.
> lib: Make image configuration always present

- lib/src/isolation.rs
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/582
> isolation: Only drop a few strategic environment variables

- lib/src/commit.rs
Since https://github.com/ostreedev/ostree-rs-ext/pull/569/commits/b5cdaf44b30814eaa5c54aa44639d52b8034c72e we are going to try really hard to just Deal With whatever content we find in `/var`.  The semantics are somewhat suboptimal, but allow people to do somewhat suboptimal things instead of not being able to do container-image based updates at all.
> commit: Drop erroring on `/var` content

- lib/src/container/encapsulate.rs
- lib/src/container/ocidir.rs
It's handy to have this be idempotent; we previously said "must be empty" but that wasn't true.
> ocidir: Change `create` -> `ensure`

- lib/src/container/mod.rs
- lib/src/container/store.rs
- lib/src/isolation.rs
@jmarrero (et all) - I have created https://github.com/ostreedev/ostree-rs-ext/tree/branch-0.12 so we can make a new release on the 0.12 series.
These two changes are on top of the last 0.12 and include one completely safe one and the desired bugfix.
isolation: Only drop a few strategic environment variables
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/582
(cherry picked from commit 263cd73b9e4d08779e2504df13a67104ab3e020c)
---
lib: Fix omitted lifetime in associated consts
See the tracking issue https://github.com/rust-lang/rust/issues/115010
There's now a warning for this in newer Rust versions.
(cherry picked from commit 939135377069c973715a2ac2f01daada06284ed8)
---
> 012 backports

- lib/src/container/encapsulate.rs
- lib/src/container/skopeo.rs
https://github.com/ostreedev/ostree-rs-ext/pull/586/commits/b104a467e9ed06663194c3b60334a5246eb988fb broke the rpm-ostree test suite, which encapsulates to a *relative* file path and so us doing `chdir` broke it.
Switch to passing down the dirfd and using `/proc/self/fd`.
(Mutable global state in `chdir` is bad)
> encapsulate: Fix regression with relative directories

- ci/priv-integration.sh
- lib/src/cli.rs
This mirrors the change done in
https://github.com/containers/bootc/pull/230/commits/20d2d6cdc1bb2ddf7f8a6884ad83efaa708b4c65
Basically our attempts to enforce this didn't really work out.
> deploy: Don't enforce container sigpolicy by default, add `--enforce-container-sigpolicy`

- lib/src/container/encapsulate.rs
See https://github.com/containers/bootc/pull/299
Since we want to move ostree more into the background, this new label name puts the focus on bootc.
> encapsulate: Add `containers.bootc` label when we add `ostree.bootable`

- cli/Cargo.toml
- lib/Cargo.toml
We really really want the MSRV-aware resolver, because we're just getting dragged on this by clap-lex bumping, when we don't have any dependency on newer versions of that really.
> Bump MSRV to 1.74

- lib/tests/it/main.rs
Let's verify the files ended up in the expected place, not just that we had no content import warnings.
> tests: Strengthen check for /usr/share/factory/var logic

- lib/src/cli.rs
- lib/src/container/store.rs
- lib/src/fixture.rs
- lib/src/tar/write.rs
- lib/tests/it/main.rs
This is intended to pair with https://github.com/ostreedev/ostree/pull/3166
If we detect a new enough ostree version, then by default don't remap
content in `/var`, assuming that ostree itself will handle it.
In order to unit test this (without depending on the ostree version
that happens to be on the host) add an API to the importer
which allows overriding the version.
---
> store: If ostree >= 2024.3, retain content in `/var`

- lib/src/container/mod.rs
Since
https://github.com/ostreedev/ostree-rs-ext/pull/594/commits/34fea14d5b6dd4b24919d4643b2c86c01273d25c we are backing off the signature verification bits.  Let's make it easier to not put those bits in the user's face by adding an alternative formatting that drops it if it's the default.
> container: Allow alternative formatting to drop `ostree-unverified-registry`

- lib/src/tar/write.rs
It turns out that the error we were seeing is that inside osbuild it wasn't mounting `/var/tmp`, and the tmpdir allocation was failing.  This was not an obvious error, so add a bunch of error contexts.
> lib/tar: Add much more error context

- lib/src/cli.rs
- lib/src/tar/write.rs
The tar code had some fancy logic to lazily allocate a temporary directory if it turned out we needed one, which only broke in the rare case we needed one in an obscure circumstance (a bwrap container in osbuild).
But we already always have a tmpdir allocated in the ostree repo, so switch the code to use that.
> tar: Unconditionally use repo tmpdir

- lib/src/fixture.rs
- lib/tests/it/main.rs
To test things related to
https://github.com/ostreedev/ostree-rs-ext/issues/607
> tests: Add an opt -> var/opt link

- lib/src/ostree_prepareroot.rs
Embarassingly this code hardcoded just one value of the tristate, which caught me out when trying to use it elsewhere.
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/612
> lib: Properly parse ostree tristate

- lib/src/globals.rs
- man/ostree-container-auth.md
This matches the general systemd design; we want to support these values being stored in `/usr` too where it can be "sealed" to the system and not locally mutable state.
> Support /usr/lib/ostree/auth.json

- lib/Cargo.toml
- lib/src/container/unencapsulate.rs
- lib/tests/it/main.rs
Fixes: https://github.com/ostreedev/ostree-rs-ext/issues/608
> Add zstd:chunked support

- lib/src/container/mod.rs
But don't serialize the layers or manifests as that's large; just the numeric diff which is a lot smaller amount of data.
Fetching manifests and layers should be done via a dedicated API.
> container: Make ManifestDiff serializable

- lib/Cargo.toml
- lib/src/container/unencapsulate.rs
- lib/tests/it/main.rs
This is basically just a workaround for https://github.com/Nullus157/async-compression/issues/271
However, in practice I think we may as well just use
a native blocking tokio thread here.
There's a lot of shenanigans going on though because
we're wrapping sync I/O with async and then back to sync
because the tar code we're using is still sync.
What would be a lot better is to move the compression to be
inline with the sync tar parsing, but that would require some
API changes and more code motion.
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/608
> container: Drop async_compression + support zstd:chunked

- lib/src/container/encapsulate.rs
This creates a `DateTime<Utc>` rather than a `NaiveDateTime` but it's what chrono recommends and, based on examining the usage of the object, doesn't change any outcomes.
> Fix use of deprecated chrono function

- lib/src/cli.rs
- lib/src/container/store.rs
- lib/src/container/unencapsulate.rs
- lib/src/container/update_detachedmeta.rs
- lib/src/fixture.rs
- lib/src/mountutil.rs
- lib/src/ostree_manual.rs
- lib/src/ostree_prepareroot.rs
- lib/src/tar/export.rs
- lib/src/tar/import.rs
- lib/src/tar/write.rs
- lib/tests/it/main.rs
> Fix clippy lints

- lib/Cargo.toml
I don't want to default to using vendored C sources.
> lib: use pkg-config feature for zstd

- lib/src/container/store.rs
This has some bearing on #388.
When importing a container image via `ostree container image pull ...`, care is taken to maintain SELinux label policy when importing the layers, vis:
https://github.com/ostreedev/ostree-rs-ext/blob/9a4743a657ffe0435018d9720c6df80a486ca0f1/lib/src/container/store.rs#L869-L876
and then in `write_tar` itself:
https://github.com/ostreedev/ostree-rs-ext/blob/9a4743a657ffe0435018d9720c6df80a486ca0f1/lib/src/tar/write.rs#L335-L343
However when it comes time to merge these layers with the base commit, we fail to apply the SELinux policy of the base commit:
https://github.com/ostreedev/ostree-rs-ext/blob/9a4743a657ffe0435018d9720c6df80a486ca0f1/lib/src/container/store.rs#L973-L985
This change adds a call to `ostree::RepoCommitModifier::set_sepolicy_from_commit()` to …
> Ensure SELinux label policy is applied when merging image layers

- lib/src/lib.rs
We currently expose a type from that, so we might as well just re-export the whole thing.
I want to do some stuff directly with containers in bootc.
> lib: Re-export containers_image_proxy in full

- cli/Cargo.toml
The 0.2 series has been dead since
https://github.com/tokio-rs/tracing/releases/tag/tracing-subscriber-0.3.0 It's long past time to update.
> cli: Bump to tracing-subscriber 0.3

- lib/src/ostree_prepareroot.rs
This was an oversight, unfortunately having two different programming languages here led to less code sharing.
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/633
> prepareroot: Also accept composefs enabled=signed

- lib/src/fixture.rs
- lib/tests/it/main.rs
fixture: Add missing trailing NUL in security.selinux xattr
Because we were only doing bare-user checkouts in the test
suite (and not trying to physically materialize the xattrs)
and because ostree today doesn't validate xattrs, this
problem was silently ignored.  But I was looking at
changing the tests to do a checkout, and this caused confusing
failures.
Add the missing trailing `NUL`.  Also while we're here,
split the xattr function in two; one which returns the
Rust-native value and a wrapper which converts to GVariant.
This will be useful later.
---
tests: Add some error context
This helped me debug a recent problem.
---
> tests: two fixes

- lib/src/container/mod.rs
- lib/src/globals.rs
- lib/src/lib.rs
Prep for having bootc directly read these as part of using podman for pulls.
While we're here:
- Use cap-std on general principle
- Change the usage to just honoring the file content directly instead of re-reading the file
- Add unit tests using that too
- Switch to using camino for paths
> Make authfile API public

- lib/src/container/mod.rs
The previous change switched to use `auth_data` directly instead of passing the file.  Update the logic just below which needs adjustment to continue to support authenticated pulls.
> proxy: Fix logic error with auth_data switch

- lib/Cargo.toml
Fixes authenticated pulls; regression from https://github.com/ostreedev/ostree-rs-ext/pull/636
> Release 0.14.1

- lib/Cargo.toml
- lib/src/chunking.rs
- lib/src/cli.rs
- lib/src/container/encapsulate.rs
- lib/src/container/store.rs
- lib/src/fixture.rs
- lib/tests/it/main.rs
chunking: Add some doc comments
Just a drive by.
---
container: Add support for re-exporting a fetched container
The status quo today is basically that with a "pure ostree"
container image, one can pull it, and one *can* re-export
it with `ostree container encapsulate`...but doing so
loses *all chunking* i.e. you end up with a single
giant layer again.
Further, we don't support exporting derived images at all.
Fix both of these with a new CLI and API, for example:
```
$ ostree container image export --repo=/path/to/repo registry:quay.io/exampleos/someos:latest containers-storage:localhost/exampleos
```
Now...before one gets too excited, this is still suboptimal
in a bunch of ways:
- Copying to `containers-storage` is super inefficient, we indirect
through a local `oci` directory because …
> container: Add support for re-exporting a fetched container

- lib/Cargo.toml
(Same as https://github.com/containers/bootc/pull/601)
> Fix deprecation warning with rust 1.79.0

- lib/src/container/encapsulate.rs
- lib/src/container/skopeo.rs
- lib/src/container/store.rs
- lib/src/container/update_detachedmeta.rs
This is a very slow operation and it'd be really
nice to have progress.
Unfortunately we don't have a sane way to propagate status from `skopeo copy`, so add an option to just output to stdout, which is usable now in bootc.
> export: Add progress flag

- lib/src/tar/write.rs
- lib/tests/it/main.rs
Because we rewrite `etc` -> `usr/etc`, we must also rewrite hardlinks.
> tar: Handle hardlinks into /etc

- lib/src/container/store.rs
- lib/src/container/unencapsulate.rs
The proxy uses shared references; prep for some
investigation of parallel unpack.
> container: Drop unnecessary &mut

- lib/Cargo.toml
- lib/src/globals.rs
Use the API from https://github.com/coreos/cap-std-ext/pull/54 to fix absolute symlinks for `/etc/ostree/auth.json`.
cc https://github.com/containers/bootc/issues/679
> config: Fix absolute symlinks

- lib/src/container/store.rs
- lib/src/integrationtest.rs
- lib/tests/it/main.rs
xref https://github.com/containers/bootc/issues/682
> Require matching architecture for bootable images

- lib/src/mountutil.rs
No major changes, just defines a const that is unavailable from the libc crate under musl.
libc does not provide STATX_ATTR_MOUNT_ROOT for the musl target as the integration for it has been slow at best. Various dependent projects have included this const manually until the libc crate itself fixes the issues with musl support.
This shouldn't change compilation on glibc-based distros as conditional-compilation is invoked.
> lib: fix building with musl libc

- lib/src/chunking.rs
- lib/src/cli.rs
- lib/src/container/store.rs
- lib/src/tar/write.rs
Mostly so when I subsequently update to use ocidir 0.3.0, I'll have a
clean slate so anything that shows up I know the update broke it.
> clippy: Fix all the things

- lib/Cargo.toml
- lib/src/chunking.rs
- lib/src/cli.rs
- lib/src/container/encapsulate.rs
- lib/src/container/mod.rs
- lib/src/container/skopeo.rs
- lib/src/container/store.rs
- lib/src/container/unencapsulate.rs
- lib/src/container/update_detachedmeta.rs
- lib/src/fixture.rs
- lib/src/integrationtest.rs
- lib/tests/it/main.rs
> Port to ocidir 0.3, containers-image-proxy 0.7

- lib/src/container/store.rs
- lib/src/container/unencapsulate.rs
- lib/src/container/update_detachedmeta.rs
- lib/tests/it/main.rs
In some places we started doing `.digest().digest()` which drops the algorithm. Some basic unit tests
would have caught this - I added one. We also need an "upgrade from previous" test.
Trying to fix this revealed a bunch more places where we had `String` and not `Digest`.
Fixing those gets us type safety and points out the problem areas.  Since we're breaking API as this will be the real first 0.15 release,
- Drop unnecessary ManifestLayerState wrappering
- Fix the manifest digest members of various structs to be a Digest
> Fix digest usage

- .github/workflows/rust.yml
- ci/priv-test-cockpit-selinux.sh
- lib/src/container/store.rs
I was initially worried this was going to slow things down but actually AFAICS because we are already setting a policy we end up rechecking the labels for all of the base image files anyways, even in the optimal
path.
So what's really happening here is we could likely speed up the non-derived case. But let's leave that as a TODO as we have much more important things.
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/510
> store: Use policy from merged tree with derived layers

- lib/src/container/unencapsulate.rs
We think this may be implicated in the mysterious "broken pipe" errors.
> unencapsulate: Add errctx for decompression

- lib/src/container/encapsulate.rs
- lib/src/container/store.rs
- lib/src/tar/write.rs
- lib/tests/it/main.rs
tar: Don't filter out toplevel /run, /proc etc
Otherwise we break things when using this code to process
a "non-ostree" image.
Signed-off-by: Colin Walters <walters@verbum.org>
---
store: Accept just containers.bootc for as bootable
This allows us to accept images to that don't have any metadata
keys starting with `ostree`.
---
> Import generic prep

- ci/installdeps.sh
Because dnf5 broke it and keeping both working is annoying and we didn't really need it.
> installdeps: drop dnf config-manager

- lib/src/container/store.rs
- lib/src/container/unencapsulate.rs
- lib/src/tar/write.rs
- lib/src/tokio_util.rs
- lib/tests/it/main.rs
This (with cautious optimism) appears to fix #657.
> Remove decompress_bridge and move decompression inline

- lib/Cargo.toml
- lib/src/tar/write.rs
- lib/tests/it/main.rs
This relies on the new tar API.
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/655
> tar: Propagate PAX extensions (including xattrs)

- lib/src/tar/write.rs
- lib/tests/it/main.rs
See https://github.com/containers/bootc/issues/856
Basically we need to handle absolute paths here too.
> tar: Handle absolute hardlinked paths to sysroot
